// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/trafficcapture"
)

// TrafficCaptureCreate is the builder for creating a TrafficCapture entity.
type TrafficCaptureCreate struct {
	config
	mutation *TrafficCaptureMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTs sets the "ts" field.
func (_c *TrafficCaptureCreate) SetTs(v time.Time) *TrafficCaptureCreate {
	_c.mutation.SetTs(v)
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *TrafficCaptureCreate) SetRequestID(v string) *TrafficCaptureCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableRequestID(v *string) *TrafficCaptureCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (_c *TrafficCaptureCreate) SetUpstreamRequestID(v string) *TrafficCaptureCreate {
	_c.mutation.SetUpstreamRequestID(v)
	return _c
}

// SetNillableUpstreamRequestID sets the "upstream_request_id" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableUpstreamRequestID(v *string) *TrafficCaptureCreate {
	if v != nil {
		_c.SetUpstreamRequestID(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *TrafficCaptureCreate) SetAPIKeyID(v int64) *TrafficCaptureCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableAPIKeyID(v *int64) *TrafficCaptureCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *TrafficCaptureCreate) SetAccountID(v int64) *TrafficCaptureCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableAccountID(v *int64) *TrafficCaptureCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *TrafficCaptureCreate) SetGroupID(v int64) *TrafficCaptureCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableGroupID(v *int64) *TrafficCaptureCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *TrafficCaptureCreate) SetPlatform(v string) *TrafficCaptureCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillablePlatform(v *string) *TrafficCaptureCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetAccountType sets the "account_type" field.
func (_c *TrafficCaptureCreate) SetAccountType(v string) *TrafficCaptureCreate {
	_c.mutation.SetAccountType(v)
	return _c
}

// SetNillableAccountType sets the "account_type" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableAccountType(v *string) *TrafficCaptureCreate {
	if v != nil {
		_c.SetAccountType(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *TrafficCaptureCreate) SetModel(v string) *TrafficCaptureCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableModel(v *string) *TrafficCaptureCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetUpstreamStatus sets the "upstream_status" field.
func (_c *TrafficCaptureCreate) SetUpstreamStatus(v int) *TrafficCaptureCreate {
	_c.mutation.SetUpstreamStatus(v)
	return _c
}

// SetNillableUpstreamStatus sets the "upstream_status" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableUpstreamStatus(v *int) *TrafficCaptureCreate {
	if v != nil {
		_c.SetUpstreamStatus(*v)
	}
	return _c
}

// SetStream sets the "stream" field.
func (_c *TrafficCaptureCreate) SetStream(v bool) *TrafficCaptureCreate {
	_c.mutation.SetStream(v)
	return _c
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableStream(v *bool) *TrafficCaptureCreate {
	if v != nil {
		_c.SetStream(*v)
	}
	return _c
}

// SetUseTimeMs sets the "use_time_ms" field.
func (_c *TrafficCaptureCreate) SetUseTimeMs(v int64) *TrafficCaptureCreate {
	_c.mutation.SetUseTimeMs(v)
	return _c
}

// SetNillableUseTimeMs sets the "use_time_ms" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableUseTimeMs(v *int64) *TrafficCaptureCreate {
	if v != nil {
		_c.SetUseTimeMs(*v)
	}
	return _c
}

// SetInboundBody sets the "inbound_body" field.
func (_c *TrafficCaptureCreate) SetInboundBody(v string) *TrafficCaptureCreate {
	_c.mutation.SetInboundBody(v)
	return _c
}

// SetNillableInboundBody sets the "inbound_body" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableInboundBody(v *string) *TrafficCaptureCreate {
	if v != nil {
		_c.SetInboundBody(*v)
	}
	return _c
}

// SetInboundBodyBytes sets the "inbound_body_bytes" field.
func (_c *TrafficCaptureCreate) SetInboundBodyBytes(v int) *TrafficCaptureCreate {
	_c.mutation.SetInboundBodyBytes(v)
	return _c
}

// SetNillableInboundBodyBytes sets the "inbound_body_bytes" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableInboundBodyBytes(v *int) *TrafficCaptureCreate {
	if v != nil {
		_c.SetInboundBodyBytes(*v)
	}
	return _c
}

// SetInboundBodyTruncated sets the "inbound_body_truncated" field.
func (_c *TrafficCaptureCreate) SetInboundBodyTruncated(v bool) *TrafficCaptureCreate {
	_c.mutation.SetInboundBodyTruncated(v)
	return _c
}

// SetNillableInboundBodyTruncated sets the "inbound_body_truncated" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableInboundBodyTruncated(v *bool) *TrafficCaptureCreate {
	if v != nil {
		_c.SetInboundBodyTruncated(*v)
	}
	return _c
}

// SetOutboundBody sets the "outbound_body" field.
func (_c *TrafficCaptureCreate) SetOutboundBody(v string) *TrafficCaptureCreate {
	_c.mutation.SetOutboundBody(v)
	return _c
}

// SetNillableOutboundBody sets the "outbound_body" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableOutboundBody(v *string) *TrafficCaptureCreate {
	if v != nil {
		_c.SetOutboundBody(*v)
	}
	return _c
}

// SetOutboundBodyBytes sets the "outbound_body_bytes" field.
func (_c *TrafficCaptureCreate) SetOutboundBodyBytes(v int) *TrafficCaptureCreate {
	_c.mutation.SetOutboundBodyBytes(v)
	return _c
}

// SetNillableOutboundBodyBytes sets the "outbound_body_bytes" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableOutboundBodyBytes(v *int) *TrafficCaptureCreate {
	if v != nil {
		_c.SetOutboundBodyBytes(*v)
	}
	return _c
}

// SetOutboundBodyTruncated sets the "outbound_body_truncated" field.
func (_c *TrafficCaptureCreate) SetOutboundBodyTruncated(v bool) *TrafficCaptureCreate {
	_c.mutation.SetOutboundBodyTruncated(v)
	return _c
}

// SetNillableOutboundBodyTruncated sets the "outbound_body_truncated" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableOutboundBodyTruncated(v *bool) *TrafficCaptureCreate {
	if v != nil {
		_c.SetOutboundBodyTruncated(*v)
	}
	return _c
}

// SetResponseBody sets the "response_body" field.
func (_c *TrafficCaptureCreate) SetResponseBody(v string) *TrafficCaptureCreate {
	_c.mutation.SetResponseBody(v)
	return _c
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableResponseBody(v *string) *TrafficCaptureCreate {
	if v != nil {
		_c.SetResponseBody(*v)
	}
	return _c
}

// SetResponseBodyBytes sets the "response_body_bytes" field.
func (_c *TrafficCaptureCreate) SetResponseBodyBytes(v int) *TrafficCaptureCreate {
	_c.mutation.SetResponseBodyBytes(v)
	return _c
}

// SetNillableResponseBodyBytes sets the "response_body_bytes" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableResponseBodyBytes(v *int) *TrafficCaptureCreate {
	if v != nil {
		_c.SetResponseBodyBytes(*v)
	}
	return _c
}

// SetResponseBodyTruncated sets the "response_body_truncated" field.
func (_c *TrafficCaptureCreate) SetResponseBodyTruncated(v bool) *TrafficCaptureCreate {
	_c.mutation.SetResponseBodyTruncated(v)
	return _c
}

// SetNillableResponseBodyTruncated sets the "response_body_truncated" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableResponseBodyTruncated(v *bool) *TrafficCaptureCreate {
	if v != nil {
		_c.SetResponseBodyTruncated(*v)
	}
	return _c
}

// SetOutboundHeaders sets the "outbound_headers" field.
func (_c *TrafficCaptureCreate) SetOutboundHeaders(v map[string]string) *TrafficCaptureCreate {
	_c.mutation.SetOutboundHeaders(v)
	return _c
}

// SetResponseHeaders sets the "response_headers" field.
func (_c *TrafficCaptureCreate) SetResponseHeaders(v map[string]string) *TrafficCaptureCreate {
	_c.mutation.SetResponseHeaders(v)
	return _c
}

// SetErrorKind sets the "error_kind" field.
func (_c *TrafficCaptureCreate) SetErrorKind(v string) *TrafficCaptureCreate {
	_c.mutation.SetErrorKind(v)
	return _c
}

// SetNillableErrorKind sets the "error_kind" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableErrorKind(v *string) *TrafficCaptureCreate {
	if v != nil {
		_c.SetErrorKind(*v)
	}
	return _c
}

// SetErrorMsg sets the "error_msg" field.
func (_c *TrafficCaptureCreate) SetErrorMsg(v string) *TrafficCaptureCreate {
	_c.mutation.SetErrorMsg(v)
	return _c
}

// SetNillableErrorMsg sets the "error_msg" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableErrorMsg(v *string) *TrafficCaptureCreate {
	if v != nil {
		_c.SetErrorMsg(*v)
	}
	return _c
}

// SetClientIP sets the "client_ip" field.
func (_c *TrafficCaptureCreate) SetClientIP(v string) *TrafficCaptureCreate {
	_c.mutation.SetClientIP(v)
	return _c
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableClientIP(v *string) *TrafficCaptureCreate {
	if v != nil {
		_c.SetClientIP(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *TrafficCaptureCreate) SetUserAgent(v string) *TrafficCaptureCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableUserAgent(v *string) *TrafficCaptureCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *TrafficCaptureCreate) SetExpiresAt(v time.Time) *TrafficCaptureCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *TrafficCaptureCreate) SetNillableExpiresAt(v *time.Time) *TrafficCaptureCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// Mutation returns the TrafficCaptureMutation object of the builder.
func (_c *TrafficCaptureCreate) Mutation() *TrafficCaptureMutation {
	return _c.mutation
}

// Save creates the TrafficCapture in the database.
func (_c *TrafficCaptureCreate) Save(ctx context.Context) (*TrafficCapture, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TrafficCaptureCreate) SaveX(ctx context.Context) *TrafficCapture {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TrafficCaptureCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TrafficCaptureCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TrafficCaptureCreate) defaults() {
	if _, ok := _c.mutation.UpstreamStatus(); !ok {
		v := trafficcapture.DefaultUpstreamStatus
		_c.mutation.SetUpstreamStatus(v)
	}
	if _, ok := _c.mutation.Stream(); !ok {
		v := trafficcapture.DefaultStream
		_c.mutation.SetStream(v)
	}
	if _, ok := _c.mutation.UseTimeMs(); !ok {
		v := trafficcapture.DefaultUseTimeMs
		_c.mutation.SetUseTimeMs(v)
	}
	if _, ok := _c.mutation.InboundBodyBytes(); !ok {
		v := trafficcapture.DefaultInboundBodyBytes
		_c.mutation.SetInboundBodyBytes(v)
	}
	if _, ok := _c.mutation.InboundBodyTruncated(); !ok {
		v := trafficcapture.DefaultInboundBodyTruncated
		_c.mutation.SetInboundBodyTruncated(v)
	}
	if _, ok := _c.mutation.OutboundBodyBytes(); !ok {
		v := trafficcapture.DefaultOutboundBodyBytes
		_c.mutation.SetOutboundBodyBytes(v)
	}
	if _, ok := _c.mutation.OutboundBodyTruncated(); !ok {
		v := trafficcapture.DefaultOutboundBodyTruncated
		_c.mutation.SetOutboundBodyTruncated(v)
	}
	if _, ok := _c.mutation.ResponseBodyBytes(); !ok {
		v := trafficcapture.DefaultResponseBodyBytes
		_c.mutation.SetResponseBodyBytes(v)
	}
	if _, ok := _c.mutation.ResponseBodyTruncated(); !ok {
		v := trafficcapture.DefaultResponseBodyTruncated
		_c.mutation.SetResponseBodyTruncated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TrafficCaptureCreate) check() error {
	if _, ok := _c.mutation.Ts(); !ok {
		return &ValidationError{Name: "ts", err: errors.New(`ent: missing required field "TrafficCapture.ts"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := trafficcapture.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.request_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UpstreamRequestID(); ok {
		if err := trafficcapture.UpstreamRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_request_id", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.upstream_request_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := trafficcapture.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.platform": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AccountType(); ok {
		if err := trafficcapture.AccountTypeValidator(v); err != nil {
			return &ValidationError{Name: "account_type", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.account_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := trafficcapture.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamStatus(); !ok {
		return &ValidationError{Name: "upstream_status", err: errors.New(`ent: missing required field "TrafficCapture.upstream_status"`)}
	}
	if _, ok := _c.mutation.Stream(); !ok {
		return &ValidationError{Name: "stream", err: errors.New(`ent: missing required field "TrafficCapture.stream"`)}
	}
	if _, ok := _c.mutation.UseTimeMs(); !ok {
		return &ValidationError{Name: "use_time_ms", err: errors.New(`ent: missing required field "TrafficCapture.use_time_ms"`)}
	}
	if _, ok := _c.mutation.InboundBodyBytes(); !ok {
		return &ValidationError{Name: "inbound_body_bytes", err: errors.New(`ent: missing required field "TrafficCapture.inbound_body_bytes"`)}
	}
	if _, ok := _c.mutation.InboundBodyTruncated(); !ok {
		return &ValidationError{Name: "inbound_body_truncated", err: errors.New(`ent: missing required field "TrafficCapture.inbound_body_truncated"`)}
	}
	if _, ok := _c.mutation.OutboundBodyBytes(); !ok {
		return &ValidationError{Name: "outbound_body_bytes", err: errors.New(`ent: missing required field "TrafficCapture.outbound_body_bytes"`)}
	}
	if _, ok := _c.mutation.OutboundBodyTruncated(); !ok {
		return &ValidationError{Name: "outbound_body_truncated", err: errors.New(`ent: missing required field "TrafficCapture.outbound_body_truncated"`)}
	}
	if _, ok := _c.mutation.ResponseBodyBytes(); !ok {
		return &ValidationError{Name: "response_body_bytes", err: errors.New(`ent: missing required field "TrafficCapture.response_body_bytes"`)}
	}
	if _, ok := _c.mutation.ResponseBodyTruncated(); !ok {
		return &ValidationError{Name: "response_body_truncated", err: errors.New(`ent: missing required field "TrafficCapture.response_body_truncated"`)}
	}
	if v, ok := _c.mutation.ErrorKind(); ok {
		if err := trafficcapture.ErrorKindValidator(v); err != nil {
			return &ValidationError{Name: "error_kind", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.error_kind": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ErrorMsg(); ok {
		if err := trafficcapture.ErrorMsgValidator(v); err != nil {
			return &ValidationError{Name: "error_msg", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.error_msg": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ClientIP(); ok {
		if err := trafficcapture.ClientIPValidator(v); err != nil {
			return &ValidationError{Name: "client_ip", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.client_ip": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UserAgent(); ok {
		if err := trafficcapture.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.user_agent": %w`, err)}
		}
	}
	return nil
}

func (_c *TrafficCaptureCreate) sqlSave(ctx context.Context) (*TrafficCapture, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TrafficCaptureCreate) createSpec() (*TrafficCapture, *sqlgraph.CreateSpec) {
	var (
		_node = &TrafficCapture{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(trafficcapture.Table, sqlgraph.NewFieldSpec(trafficcapture.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Ts(); ok {
		_spec.SetField(trafficcapture.FieldTs, field.TypeTime, value)
		_node.Ts = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(trafficcapture.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.UpstreamRequestID(); ok {
		_spec.SetField(trafficcapture.FieldUpstreamRequestID, field.TypeString, value)
		_node.UpstreamRequestID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(trafficcapture.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(trafficcapture.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(trafficcapture.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(trafficcapture.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.AccountType(); ok {
		_spec.SetField(trafficcapture.FieldAccountType, field.TypeString, value)
		_node.AccountType = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(trafficcapture.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.UpstreamStatus(); ok {
		_spec.SetField(trafficcapture.FieldUpstreamStatus, field.TypeInt, value)
		_node.UpstreamStatus = value
	}
	if value, ok := _c.mutation.Stream(); ok {
		_spec.SetField(trafficcapture.FieldStream, field.TypeBool, value)
		_node.Stream = value
	}
	if value, ok := _c.mutation.UseTimeMs(); ok {
		_spec.SetField(trafficcapture.FieldUseTimeMs, field.TypeInt64, value)
		_node.UseTimeMs = value
	}
	if value, ok := _c.mutation.InboundBody(); ok {
		_spec.SetField(trafficcapture.FieldInboundBody, field.TypeString, value)
		_node.InboundBody = value
	}
	if value, ok := _c.mutation.InboundBodyBytes(); ok {
		_spec.SetField(trafficcapture.FieldInboundBodyBytes, field.TypeInt, value)
		_node.InboundBodyBytes = value
	}
	if value, ok := _c.mutation.InboundBodyTruncated(); ok {
		_spec.SetField(trafficcapture.FieldInboundBodyTruncated, field.TypeBool, value)
		_node.InboundBodyTruncated = value
	}
	if value, ok := _c.mutation.OutboundBody(); ok {
		_spec.SetField(trafficcapture.FieldOutboundBody, field.TypeString, value)
		_node.OutboundBody = value
	}
	if value, ok := _c.mutation.OutboundBodyBytes(); ok {
		_spec.SetField(trafficcapture.FieldOutboundBodyBytes, field.TypeInt, value)
		_node.OutboundBodyBytes = value
	}
	if value, ok := _c.mutation.OutboundBodyTruncated(); ok {
		_spec.SetField(trafficcapture.FieldOutboundBodyTruncated, field.TypeBool, value)
		_node.OutboundBodyTruncated = value
	}
	if value, ok := _c.mutation.ResponseBody(); ok {
		_spec.SetField(trafficcapture.FieldResponseBody, field.TypeString, value)
		_node.ResponseBody = value
	}
	if value, ok := _c.mutation.ResponseBodyBytes(); ok {
		_spec.SetField(trafficcapture.FieldResponseBodyBytes, field.TypeInt, value)
		_node.ResponseBodyBytes = value
	}
	if value, ok := _c.mutation.ResponseBodyTruncated(); ok {
		_spec.SetField(trafficcapture.FieldResponseBodyTruncated, field.TypeBool, value)
		_node.ResponseBodyTruncated = value
	}
	if value, ok := _c.mutation.OutboundHeaders(); ok {
		_spec.SetField(trafficcapture.FieldOutboundHeaders, field.TypeJSON, value)
		_node.OutboundHeaders = value
	}
	if value, ok := _c.mutation.ResponseHeaders(); ok {
		_spec.SetField(trafficcapture.FieldResponseHeaders, field.TypeJSON, value)
		_node.ResponseHeaders = value
	}
	if value, ok := _c.mutation.ErrorKind(); ok {
		_spec.SetField(trafficcapture.FieldErrorKind, field.TypeString, value)
		_node.ErrorKind = value
	}
	if value, ok := _c.mutation.ErrorMsg(); ok {
		_spec.SetField(trafficcapture.FieldErrorMsg, field.TypeString, value)
		_node.ErrorMsg = value
	}
	if value, ok := _c.mutation.ClientIP(); ok {
		_spec.SetField(trafficcapture.FieldClientIP, field.TypeString, value)
		_node.ClientIP = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(trafficcapture.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(trafficcapture.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TrafficCapture.Create().
//		SetTs(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TrafficCaptureUpsert) {
//			SetTs(v+v).
//		}).
//		Exec(ctx)
func (_c *TrafficCaptureCreate) OnConflict(opts ...sql.ConflictOption) *TrafficCaptureUpsertOne {
	_c.conflict = opts
	return &TrafficCaptureUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TrafficCapture.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TrafficCaptureCreate) OnConflictColumns(columns ...string) *TrafficCaptureUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TrafficCaptureUpsertOne{
		create: _c,
	}
}

type (
	// TrafficCaptureUpsertOne is the builder for "upsert"-ing
	//  one TrafficCapture node.
	TrafficCaptureUpsertOne struct {
		create *TrafficCaptureCreate
	}

	// TrafficCaptureUpsert is the "OnConflict" setter.
	TrafficCaptureUpsert struct {
		*sql.UpdateSet
	}
)

// SetRequestID sets the "request_id" field.
func (u *TrafficCaptureUpsert) SetRequestID(v string) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateRequestID() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldRequestID)
	return u
}

// ClearRequestID clears the value of the "request_id" field.
func (u *TrafficCaptureUpsert) ClearRequestID() *TrafficCaptureUpsert {
	u.SetNull(trafficcapture.FieldRequestID)
	return u
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (u *TrafficCaptureUpsert) SetUpstreamRequestID(v string) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldUpstreamRequestID, v)
	return u
}

// UpdateUpstreamRequestID sets the "upstream_request_id" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateUpstreamRequestID() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldUpstreamRequestID)
	return u
}

// ClearUpstreamRequestID clears the value of the "upstream_request_id" field.
func (u *TrafficCaptureUpsert) ClearUpstreamRequestID() *TrafficCaptureUpsert {
	u.SetNull(trafficcapture.FieldUpstreamRequestID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *TrafficCaptureUpsert) SetAPIKeyID(v int64) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateAPIKeyID() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *TrafficCaptureUpsert) AddAPIKeyID(v int64) *TrafficCaptureUpsert {
	u.Add(trafficcapture.FieldAPIKeyID, v)
	return u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *TrafficCaptureUpsert) ClearAPIKeyID() *TrafficCaptureUpsert {
	u.SetNull(trafficcapture.FieldAPIKeyID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *TrafficCaptureUpsert) SetAccountID(v int64) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateAccountID() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *TrafficCaptureUpsert) AddAccountID(v int64) *TrafficCaptureUpsert {
	u.Add(trafficcapture.FieldAccountID, v)
	return u
}

// ClearAccountID clears the value of the "account_id" field.
func (u *TrafficCaptureUpsert) ClearAccountID() *TrafficCaptureUpsert {
	u.SetNull(trafficcapture.FieldAccountID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *TrafficCaptureUpsert) SetGroupID(v int64) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateGroupID() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *TrafficCaptureUpsert) AddGroupID(v int64) *TrafficCaptureUpsert {
	u.Add(trafficcapture.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *TrafficCaptureUpsert) ClearGroupID() *TrafficCaptureUpsert {
	u.SetNull(trafficcapture.FieldGroupID)
	return u
}

// SetPlatform sets the "platform" field.
func (u *TrafficCaptureUpsert) SetPlatform(v string) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdatePlatform() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldPlatform)
	return u
}

// ClearPlatform clears the value of the "platform" field.
func (u *TrafficCaptureUpsert) ClearPlatform() *TrafficCaptureUpsert {
	u.SetNull(trafficcapture.FieldPlatform)
	return u
}

// SetAccountType sets the "account_type" field.
func (u *TrafficCaptureUpsert) SetAccountType(v string) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldAccountType, v)
	return u
}

// UpdateAccountType sets the "account_type" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateAccountType() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldAccountType)
	return u
}

// ClearAccountType clears the value of the "account_type" field.
func (u *TrafficCaptureUpsert) ClearAccountType() *TrafficCaptureUpsert {
	u.SetNull(trafficcapture.FieldAccountType)
	return u
}

// SetModel sets the "model" field.
func (u *TrafficCaptureUpsert) SetModel(v string) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateModel() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldModel)
	return u
}

// ClearModel clears the value of the "model" field.
func (u *TrafficCaptureUpsert) ClearModel() *TrafficCaptureUpsert {
	u.SetNull(trafficcapture.FieldModel)
	return u
}

// SetUpstreamStatus sets the "upstream_status" field.
func (u *TrafficCaptureUpsert) SetUpstreamStatus(v int) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldUpstreamStatus, v)
	return u
}

// UpdateUpstreamStatus sets the "upstream_status" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateUpstreamStatus() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldUpstreamStatus)
	return u
}

// AddUpstreamStatus adds v to the "upstream_status" field.
func (u *TrafficCaptureUpsert) AddUpstreamStatus(v int) *TrafficCaptureUpsert {
	u.Add(trafficcapture.FieldUpstreamStatus, v)
	return u
}

// SetStream sets the "stream" field.
func (u *TrafficCaptureUpsert) SetStream(v bool) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldStream, v)
	return u
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateStream() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldStream)
	return u
}

// SetUseTimeMs sets the "use_time_ms" field.
func (u *TrafficCaptureUpsert) SetUseTimeMs(v int64) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldUseTimeMs, v)
	return u
}

// UpdateUseTimeMs sets the "use_time_ms" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateUseTimeMs() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldUseTimeMs)
	return u
}

// AddUseTimeMs adds v to the "use_time_ms" field.
func (u *TrafficCaptureUpsert) AddUseTimeMs(v int64) *TrafficCaptureUpsert {
	u.Add(trafficcapture.FieldUseTimeMs, v)
	return u
}

// SetInboundBody sets the "inbound_body" field.
func (u *TrafficCaptureUpsert) SetInboundBody(v string) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldInboundBody, v)
	return u
}

// UpdateInboundBody sets the "inbound_body" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateInboundBody() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldInboundBody)
	return u
}

// ClearInboundBody clears the value of the "inbound_body" field.
func (u *TrafficCaptureUpsert) ClearInboundBody() *TrafficCaptureUpsert {
	u.SetNull(trafficcapture.FieldInboundBody)
	return u
}

// SetInboundBodyBytes sets the "inbound_body_bytes" field.
func (u *TrafficCaptureUpsert) SetInboundBodyBytes(v int) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldInboundBodyBytes, v)
	return u
}

// UpdateInboundBodyBytes sets the "inbound_body_bytes" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateInboundBodyBytes() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldInboundBodyBytes)
	return u
}

// AddInboundBodyBytes adds v to the "inbound_body_bytes" field.
func (u *TrafficCaptureUpsert) AddInboundBodyBytes(v int) *TrafficCaptureUpsert {
	u.Add(trafficcapture.FieldInboundBodyBytes, v)
	return u
}

// SetInboundBodyTruncated sets the "inbound_body_truncated" field.
func (u *TrafficCaptureUpsert) SetInboundBodyTruncated(v bool) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldInboundBodyTruncated, v)
	return u
}

// UpdateInboundBodyTruncated sets the "inbound_body_truncated" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateInboundBodyTruncated() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldInboundBodyTruncated)
	return u
}

// SetOutboundBody sets the "outbound_body" field.
func (u *TrafficCaptureUpsert) SetOutboundBody(v string) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldOutboundBody, v)
	return u
}

// UpdateOutboundBody sets the "outbound_body" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateOutboundBody() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldOutboundBody)
	return u
}

// ClearOutboundBody clears the value of the "outbound_body" field.
func (u *TrafficCaptureUpsert) ClearOutboundBody() *TrafficCaptureUpsert {
	u.SetNull(trafficcapture.FieldOutboundBody)
	return u
}

// SetOutboundBodyBytes sets the "outbound_body_bytes" field.
func (u *TrafficCaptureUpsert) SetOutboundBodyBytes(v int) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldOutboundBodyBytes, v)
	return u
}

// UpdateOutboundBodyBytes sets the "outbound_body_bytes" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateOutboundBodyBytes() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldOutboundBodyBytes)
	return u
}

// AddOutboundBodyBytes adds v to the "outbound_body_bytes" field.
func (u *TrafficCaptureUpsert) AddOutboundBodyBytes(v int) *TrafficCaptureUpsert {
	u.Add(trafficcapture.FieldOutboundBodyBytes, v)
	return u
}

// SetOutboundBodyTruncated sets the "outbound_body_truncated" field.
func (u *TrafficCaptureUpsert) SetOutboundBodyTruncated(v bool) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldOutboundBodyTruncated, v)
	return u
}

// UpdateOutboundBodyTruncated sets the "outbound_body_truncated" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateOutboundBodyTruncated() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldOutboundBodyTruncated)
	return u
}

// SetResponseBody sets the "response_body" field.
func (u *TrafficCaptureUpsert) SetResponseBody(v string) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldResponseBody, v)
	return u
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateResponseBody() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldResponseBody)
	return u
}

// ClearResponseBody clears the value of the "response_body" field.
func (u *TrafficCaptureUpsert) ClearResponseBody() *TrafficCaptureUpsert {
	u.SetNull(trafficcapture.FieldResponseBody)
	return u
}

// SetResponseBodyBytes sets the "response_body_bytes" field.
func (u *TrafficCaptureUpsert) SetResponseBodyBytes(v int) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldResponseBodyBytes, v)
	return u
}

// UpdateResponseBodyBytes sets the "response_body_bytes" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateResponseBodyBytes() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldResponseBodyBytes)
	return u
}

// AddResponseBodyBytes adds v to the "response_body_bytes" field.
func (u *TrafficCaptureUpsert) AddResponseBodyBytes(v int) *TrafficCaptureUpsert {
	u.Add(trafficcapture.FieldResponseBodyBytes, v)
	return u
}

// SetResponseBodyTruncated sets the "response_body_truncated" field.
func (u *TrafficCaptureUpsert) SetResponseBodyTruncated(v bool) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldResponseBodyTruncated, v)
	return u
}

// UpdateResponseBodyTruncated sets the "response_body_truncated" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateResponseBodyTruncated() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldResponseBodyTruncated)
	return u
}

// SetOutboundHeaders sets the "outbound_headers" field.
func (u *TrafficCaptureUpsert) SetOutboundHeaders(v map[string]string) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldOutboundHeaders, v)
	return u
}

// UpdateOutboundHeaders sets the "outbound_headers" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateOutboundHeaders() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldOutboundHeaders)
	return u
}

// ClearOutboundHeaders clears the value of the "outbound_headers" field.
func (u *TrafficCaptureUpsert) ClearOutboundHeaders() *TrafficCaptureUpsert {
	u.SetNull(trafficcapture.FieldOutboundHeaders)
	return u
}

// SetResponseHeaders sets the "response_headers" field.
func (u *TrafficCaptureUpsert) SetResponseHeaders(v map[string]string) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldResponseHeaders, v)
	return u
}

// UpdateResponseHeaders sets the "response_headers" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateResponseHeaders() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldResponseHeaders)
	return u
}

// ClearResponseHeaders clears the value of the "response_headers" field.
func (u *TrafficCaptureUpsert) ClearResponseHeaders() *TrafficCaptureUpsert {
	u.SetNull(trafficcapture.FieldResponseHeaders)
	return u
}

// SetErrorKind sets the "error_kind" field.
func (u *TrafficCaptureUpsert) SetErrorKind(v string) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldErrorKind, v)
	return u
}

// UpdateErrorKind sets the "error_kind" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateErrorKind() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldErrorKind)
	return u
}

// ClearErrorKind clears the value of the "error_kind" field.
func (u *TrafficCaptureUpsert) ClearErrorKind() *TrafficCaptureUpsert {
	u.SetNull(trafficcapture.FieldErrorKind)
	return u
}

// SetErrorMsg sets the "error_msg" field.
func (u *TrafficCaptureUpsert) SetErrorMsg(v string) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldErrorMsg, v)
	return u
}

// UpdateErrorMsg sets the "error_msg" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateErrorMsg() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldErrorMsg)
	return u
}

// ClearErrorMsg clears the value of the "error_msg" field.
func (u *TrafficCaptureUpsert) ClearErrorMsg() *TrafficCaptureUpsert {
	u.SetNull(trafficcapture.FieldErrorMsg)
	return u
}

// SetClientIP sets the "client_ip" field.
func (u *TrafficCaptureUpsert) SetClientIP(v string) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldClientIP, v)
	return u
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateClientIP() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldClientIP)
	return u
}

// ClearClientIP clears the value of the "client_ip" field.
func (u *TrafficCaptureUpsert) ClearClientIP() *TrafficCaptureUpsert {
	u.SetNull(trafficcapture.FieldClientIP)
	return u
}

// SetUserAgent sets the "user_agent" field.
func (u *TrafficCaptureUpsert) SetUserAgent(v string) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldUserAgent, v)
	return u
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateUserAgent() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldUserAgent)
	return u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *TrafficCaptureUpsert) ClearUserAgent() *TrafficCaptureUpsert {
	u.SetNull(trafficcapture.FieldUserAgent)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *TrafficCaptureUpsert) SetExpiresAt(v time.Time) *TrafficCaptureUpsert {
	u.Set(trafficcapture.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *TrafficCaptureUpsert) UpdateExpiresAt() *TrafficCaptureUpsert {
	u.SetExcluded(trafficcapture.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *TrafficCaptureUpsert) ClearExpiresAt() *TrafficCaptureUpsert {
	u.SetNull(trafficcapture.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TrafficCapture.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TrafficCaptureUpsertOne) UpdateNewValues() *TrafficCaptureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.Ts(); exists {
			s.SetIgnore(trafficcapture.FieldTs)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TrafficCapture.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TrafficCaptureUpsertOne) Ignore() *TrafficCaptureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TrafficCaptureUpsertOne) DoNothing() *TrafficCaptureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TrafficCaptureCreate.OnConflict
// documentation for more info.
func (u *TrafficCaptureUpsertOne) Update(set func(*TrafficCaptureUpsert)) *TrafficCaptureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TrafficCaptureUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *TrafficCaptureUpsertOne) SetRequestID(v string) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateRequestID() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *TrafficCaptureUpsertOne) ClearRequestID() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearRequestID()
	})
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (u *TrafficCaptureUpsertOne) SetUpstreamRequestID(v string) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetUpstreamRequestID(v)
	})
}

// UpdateUpstreamRequestID sets the "upstream_request_id" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateUpstreamRequestID() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateUpstreamRequestID()
	})
}

// ClearUpstreamRequestID clears the value of the "upstream_request_id" field.
func (u *TrafficCaptureUpsertOne) ClearUpstreamRequestID() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearUpstreamRequestID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *TrafficCaptureUpsertOne) SetAPIKeyID(v int64) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *TrafficCaptureUpsertOne) AddAPIKeyID(v int64) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateAPIKeyID() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *TrafficCaptureUpsertOne) ClearAPIKeyID() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *TrafficCaptureUpsertOne) SetAccountID(v int64) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *TrafficCaptureUpsertOne) AddAccountID(v int64) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateAccountID() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *TrafficCaptureUpsertOne) ClearAccountID() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearAccountID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *TrafficCaptureUpsertOne) SetGroupID(v int64) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *TrafficCaptureUpsertOne) AddGroupID(v int64) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateGroupID() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *TrafficCaptureUpsertOne) ClearGroupID() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearGroupID()
	})
}

// SetPlatform sets the "platform" field.
func (u *TrafficCaptureUpsertOne) SetPlatform(v string) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdatePlatform() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdatePlatform()
	})
}

// ClearPlatform clears the value of the "platform" field.
func (u *TrafficCaptureUpsertOne) ClearPlatform() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearPlatform()
	})
}

// SetAccountType sets the "account_type" field.
func (u *TrafficCaptureUpsertOne) SetAccountType(v string) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetAccountType(v)
	})
}

// UpdateAccountType sets the "account_type" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateAccountType() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateAccountType()
	})
}

// ClearAccountType clears the value of the "account_type" field.
func (u *TrafficCaptureUpsertOne) ClearAccountType() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearAccountType()
	})
}

// SetModel sets the "model" field.
func (u *TrafficCaptureUpsertOne) SetModel(v string) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateModel() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *TrafficCaptureUpsertOne) ClearModel() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearModel()
	})
}

// SetUpstreamStatus sets the "upstream_status" field.
func (u *TrafficCaptureUpsertOne) SetUpstreamStatus(v int) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetUpstreamStatus(v)
	})
}

// AddUpstreamStatus adds v to the "upstream_status" field.
func (u *TrafficCaptureUpsertOne) AddUpstreamStatus(v int) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.AddUpstreamStatus(v)
	})
}

// UpdateUpstreamStatus sets the "upstream_status" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateUpstreamStatus() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateUpstreamStatus()
	})
}

// SetStream sets the "stream" field.
func (u *TrafficCaptureUpsertOne) SetStream(v bool) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetStream(v)
	})
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateStream() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateStream()
	})
}

// SetUseTimeMs sets the "use_time_ms" field.
func (u *TrafficCaptureUpsertOne) SetUseTimeMs(v int64) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetUseTimeMs(v)
	})
}

// AddUseTimeMs adds v to the "use_time_ms" field.
func (u *TrafficCaptureUpsertOne) AddUseTimeMs(v int64) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.AddUseTimeMs(v)
	})
}

// UpdateUseTimeMs sets the "use_time_ms" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateUseTimeMs() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateUseTimeMs()
	})
}

// SetInboundBody sets the "inbound_body" field.
func (u *TrafficCaptureUpsertOne) SetInboundBody(v string) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetInboundBody(v)
	})
}

// UpdateInboundBody sets the "inbound_body" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateInboundBody() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateInboundBody()
	})
}

// ClearInboundBody clears the value of the "inbound_body" field.
func (u *TrafficCaptureUpsertOne) ClearInboundBody() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearInboundBody()
	})
}

// SetInboundBodyBytes sets the "inbound_body_bytes" field.
func (u *TrafficCaptureUpsertOne) SetInboundBodyBytes(v int) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetInboundBodyBytes(v)
	})
}

// AddInboundBodyBytes adds v to the "inbound_body_bytes" field.
func (u *TrafficCaptureUpsertOne) AddInboundBodyBytes(v int) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.AddInboundBodyBytes(v)
	})
}

// UpdateInboundBodyBytes sets the "inbound_body_bytes" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateInboundBodyBytes() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateInboundBodyBytes()
	})
}

// SetInboundBodyTruncated sets the "inbound_body_truncated" field.
func (u *TrafficCaptureUpsertOne) SetInboundBodyTruncated(v bool) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetInboundBodyTruncated(v)
	})
}

// UpdateInboundBodyTruncated sets the "inbound_body_truncated" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateInboundBodyTruncated() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateInboundBodyTruncated()
	})
}

// SetOutboundBody sets the "outbound_body" field.
func (u *TrafficCaptureUpsertOne) SetOutboundBody(v string) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetOutboundBody(v)
	})
}

// UpdateOutboundBody sets the "outbound_body" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateOutboundBody() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateOutboundBody()
	})
}

// ClearOutboundBody clears the value of the "outbound_body" field.
func (u *TrafficCaptureUpsertOne) ClearOutboundBody() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearOutboundBody()
	})
}

// SetOutboundBodyBytes sets the "outbound_body_bytes" field.
func (u *TrafficCaptureUpsertOne) SetOutboundBodyBytes(v int) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetOutboundBodyBytes(v)
	})
}

// AddOutboundBodyBytes adds v to the "outbound_body_bytes" field.
func (u *TrafficCaptureUpsertOne) AddOutboundBodyBytes(v int) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.AddOutboundBodyBytes(v)
	})
}

// UpdateOutboundBodyBytes sets the "outbound_body_bytes" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateOutboundBodyBytes() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateOutboundBodyBytes()
	})
}

// SetOutboundBodyTruncated sets the "outbound_body_truncated" field.
func (u *TrafficCaptureUpsertOne) SetOutboundBodyTruncated(v bool) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetOutboundBodyTruncated(v)
	})
}

// UpdateOutboundBodyTruncated sets the "outbound_body_truncated" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateOutboundBodyTruncated() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateOutboundBodyTruncated()
	})
}

// SetResponseBody sets the "response_body" field.
func (u *TrafficCaptureUpsertOne) SetResponseBody(v string) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetResponseBody(v)
	})
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateResponseBody() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateResponseBody()
	})
}

// ClearResponseBody clears the value of the "response_body" field.
func (u *TrafficCaptureUpsertOne) ClearResponseBody() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearResponseBody()
	})
}

// SetResponseBodyBytes sets the "response_body_bytes" field.
func (u *TrafficCaptureUpsertOne) SetResponseBodyBytes(v int) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetResponseBodyBytes(v)
	})
}

// AddResponseBodyBytes adds v to the "response_body_bytes" field.
func (u *TrafficCaptureUpsertOne) AddResponseBodyBytes(v int) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.AddResponseBodyBytes(v)
	})
}

// UpdateResponseBodyBytes sets the "response_body_bytes" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateResponseBodyBytes() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateResponseBodyBytes()
	})
}

// SetResponseBodyTruncated sets the "response_body_truncated" field.
func (u *TrafficCaptureUpsertOne) SetResponseBodyTruncated(v bool) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetResponseBodyTruncated(v)
	})
}

// UpdateResponseBodyTruncated sets the "response_body_truncated" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateResponseBodyTruncated() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateResponseBodyTruncated()
	})
}

// SetOutboundHeaders sets the "outbound_headers" field.
func (u *TrafficCaptureUpsertOne) SetOutboundHeaders(v map[string]string) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetOutboundHeaders(v)
	})
}

// UpdateOutboundHeaders sets the "outbound_headers" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateOutboundHeaders() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateOutboundHeaders()
	})
}

// ClearOutboundHeaders clears the value of the "outbound_headers" field.
func (u *TrafficCaptureUpsertOne) ClearOutboundHeaders() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearOutboundHeaders()
	})
}

// SetResponseHeaders sets the "response_headers" field.
func (u *TrafficCaptureUpsertOne) SetResponseHeaders(v map[string]string) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetResponseHeaders(v)
	})
}

// UpdateResponseHeaders sets the "response_headers" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateResponseHeaders() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateResponseHeaders()
	})
}

// ClearResponseHeaders clears the value of the "response_headers" field.
func (u *TrafficCaptureUpsertOne) ClearResponseHeaders() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearResponseHeaders()
	})
}

// SetErrorKind sets the "error_kind" field.
func (u *TrafficCaptureUpsertOne) SetErrorKind(v string) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetErrorKind(v)
	})
}

// UpdateErrorKind sets the "error_kind" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateErrorKind() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateErrorKind()
	})
}

// ClearErrorKind clears the value of the "error_kind" field.
func (u *TrafficCaptureUpsertOne) ClearErrorKind() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearErrorKind()
	})
}

// SetErrorMsg sets the "error_msg" field.
func (u *TrafficCaptureUpsertOne) SetErrorMsg(v string) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetErrorMsg(v)
	})
}

// UpdateErrorMsg sets the "error_msg" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateErrorMsg() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateErrorMsg()
	})
}

// ClearErrorMsg clears the value of the "error_msg" field.
func (u *TrafficCaptureUpsertOne) ClearErrorMsg() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearErrorMsg()
	})
}

// SetClientIP sets the "client_ip" field.
func (u *TrafficCaptureUpsertOne) SetClientIP(v string) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetClientIP(v)
	})
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateClientIP() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateClientIP()
	})
}

// ClearClientIP clears the value of the "client_ip" field.
func (u *TrafficCaptureUpsertOne) ClearClientIP() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearClientIP()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *TrafficCaptureUpsertOne) SetUserAgent(v string) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateUserAgent() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *TrafficCaptureUpsertOne) ClearUserAgent() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearUserAgent()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *TrafficCaptureUpsertOne) SetExpiresAt(v time.Time) *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *TrafficCaptureUpsertOne) UpdateExpiresAt() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *TrafficCaptureUpsertOne) ClearExpiresAt() *TrafficCaptureUpsertOne {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *TrafficCaptureUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TrafficCaptureCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TrafficCaptureUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TrafficCaptureUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TrafficCaptureUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TrafficCaptureCreateBulk is the builder for creating many TrafficCapture entities in bulk.
type TrafficCaptureCreateBulk struct {
	config
	err      error
	builders []*TrafficCaptureCreate
	conflict []sql.ConflictOption
}

// Save creates the TrafficCapture entities in the database.
func (_c *TrafficCaptureCreateBulk) Save(ctx context.Context) ([]*TrafficCapture, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TrafficCapture, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TrafficCaptureMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TrafficCaptureCreateBulk) SaveX(ctx context.Context) []*TrafficCapture {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TrafficCaptureCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TrafficCaptureCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TrafficCapture.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TrafficCaptureUpsert) {
//			SetTs(v+v).
//		}).
//		Exec(ctx)
func (_c *TrafficCaptureCreateBulk) OnConflict(opts ...sql.ConflictOption) *TrafficCaptureUpsertBulk {
	_c.conflict = opts
	return &TrafficCaptureUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TrafficCapture.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TrafficCaptureCreateBulk) OnConflictColumns(columns ...string) *TrafficCaptureUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TrafficCaptureUpsertBulk{
		create: _c,
	}
}

// TrafficCaptureUpsertBulk is the builder for "upsert"-ing
// a bulk of TrafficCapture nodes.
type TrafficCaptureUpsertBulk struct {
	create *TrafficCaptureCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TrafficCapture.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TrafficCaptureUpsertBulk) UpdateNewValues() *TrafficCaptureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.Ts(); exists {
				s.SetIgnore(trafficcapture.FieldTs)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TrafficCapture.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TrafficCaptureUpsertBulk) Ignore() *TrafficCaptureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TrafficCaptureUpsertBulk) DoNothing() *TrafficCaptureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TrafficCaptureCreateBulk.OnConflict
// documentation for more info.
func (u *TrafficCaptureUpsertBulk) Update(set func(*TrafficCaptureUpsert)) *TrafficCaptureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TrafficCaptureUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *TrafficCaptureUpsertBulk) SetRequestID(v string) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateRequestID() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *TrafficCaptureUpsertBulk) ClearRequestID() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearRequestID()
	})
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (u *TrafficCaptureUpsertBulk) SetUpstreamRequestID(v string) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetUpstreamRequestID(v)
	})
}

// UpdateUpstreamRequestID sets the "upstream_request_id" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateUpstreamRequestID() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateUpstreamRequestID()
	})
}

// ClearUpstreamRequestID clears the value of the "upstream_request_id" field.
func (u *TrafficCaptureUpsertBulk) ClearUpstreamRequestID() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearUpstreamRequestID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *TrafficCaptureUpsertBulk) SetAPIKeyID(v int64) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *TrafficCaptureUpsertBulk) AddAPIKeyID(v int64) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateAPIKeyID() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *TrafficCaptureUpsertBulk) ClearAPIKeyID() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *TrafficCaptureUpsertBulk) SetAccountID(v int64) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *TrafficCaptureUpsertBulk) AddAccountID(v int64) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateAccountID() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *TrafficCaptureUpsertBulk) ClearAccountID() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearAccountID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *TrafficCaptureUpsertBulk) SetGroupID(v int64) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *TrafficCaptureUpsertBulk) AddGroupID(v int64) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateGroupID() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *TrafficCaptureUpsertBulk) ClearGroupID() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearGroupID()
	})
}

// SetPlatform sets the "platform" field.
func (u *TrafficCaptureUpsertBulk) SetPlatform(v string) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdatePlatform() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdatePlatform()
	})
}

// ClearPlatform clears the value of the "platform" field.
func (u *TrafficCaptureUpsertBulk) ClearPlatform() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearPlatform()
	})
}

// SetAccountType sets the "account_type" field.
func (u *TrafficCaptureUpsertBulk) SetAccountType(v string) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetAccountType(v)
	})
}

// UpdateAccountType sets the "account_type" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateAccountType() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateAccountType()
	})
}

// ClearAccountType clears the value of the "account_type" field.
func (u *TrafficCaptureUpsertBulk) ClearAccountType() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearAccountType()
	})
}

// SetModel sets the "model" field.
func (u *TrafficCaptureUpsertBulk) SetModel(v string) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateModel() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *TrafficCaptureUpsertBulk) ClearModel() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearModel()
	})
}

// SetUpstreamStatus sets the "upstream_status" field.
func (u *TrafficCaptureUpsertBulk) SetUpstreamStatus(v int) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetUpstreamStatus(v)
	})
}

// AddUpstreamStatus adds v to the "upstream_status" field.
func (u *TrafficCaptureUpsertBulk) AddUpstreamStatus(v int) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.AddUpstreamStatus(v)
	})
}

// UpdateUpstreamStatus sets the "upstream_status" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateUpstreamStatus() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateUpstreamStatus()
	})
}

// SetStream sets the "stream" field.
func (u *TrafficCaptureUpsertBulk) SetStream(v bool) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetStream(v)
	})
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateStream() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateStream()
	})
}

// SetUseTimeMs sets the "use_time_ms" field.
func (u *TrafficCaptureUpsertBulk) SetUseTimeMs(v int64) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetUseTimeMs(v)
	})
}

// AddUseTimeMs adds v to the "use_time_ms" field.
func (u *TrafficCaptureUpsertBulk) AddUseTimeMs(v int64) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.AddUseTimeMs(v)
	})
}

// UpdateUseTimeMs sets the "use_time_ms" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateUseTimeMs() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateUseTimeMs()
	})
}

// SetInboundBody sets the "inbound_body" field.
func (u *TrafficCaptureUpsertBulk) SetInboundBody(v string) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetInboundBody(v)
	})
}

// UpdateInboundBody sets the "inbound_body" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateInboundBody() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateInboundBody()
	})
}

// ClearInboundBody clears the value of the "inbound_body" field.
func (u *TrafficCaptureUpsertBulk) ClearInboundBody() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearInboundBody()
	})
}

// SetInboundBodyBytes sets the "inbound_body_bytes" field.
func (u *TrafficCaptureUpsertBulk) SetInboundBodyBytes(v int) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetInboundBodyBytes(v)
	})
}

// AddInboundBodyBytes adds v to the "inbound_body_bytes" field.
func (u *TrafficCaptureUpsertBulk) AddInboundBodyBytes(v int) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.AddInboundBodyBytes(v)
	})
}

// UpdateInboundBodyBytes sets the "inbound_body_bytes" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateInboundBodyBytes() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateInboundBodyBytes()
	})
}

// SetInboundBodyTruncated sets the "inbound_body_truncated" field.
func (u *TrafficCaptureUpsertBulk) SetInboundBodyTruncated(v bool) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetInboundBodyTruncated(v)
	})
}

// UpdateInboundBodyTruncated sets the "inbound_body_truncated" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateInboundBodyTruncated() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateInboundBodyTruncated()
	})
}

// SetOutboundBody sets the "outbound_body" field.
func (u *TrafficCaptureUpsertBulk) SetOutboundBody(v string) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetOutboundBody(v)
	})
}

// UpdateOutboundBody sets the "outbound_body" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateOutboundBody() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateOutboundBody()
	})
}

// ClearOutboundBody clears the value of the "outbound_body" field.
func (u *TrafficCaptureUpsertBulk) ClearOutboundBody() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearOutboundBody()
	})
}

// SetOutboundBodyBytes sets the "outbound_body_bytes" field.
func (u *TrafficCaptureUpsertBulk) SetOutboundBodyBytes(v int) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetOutboundBodyBytes(v)
	})
}

// AddOutboundBodyBytes adds v to the "outbound_body_bytes" field.
func (u *TrafficCaptureUpsertBulk) AddOutboundBodyBytes(v int) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.AddOutboundBodyBytes(v)
	})
}

// UpdateOutboundBodyBytes sets the "outbound_body_bytes" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateOutboundBodyBytes() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateOutboundBodyBytes()
	})
}

// SetOutboundBodyTruncated sets the "outbound_body_truncated" field.
func (u *TrafficCaptureUpsertBulk) SetOutboundBodyTruncated(v bool) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetOutboundBodyTruncated(v)
	})
}

// UpdateOutboundBodyTruncated sets the "outbound_body_truncated" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateOutboundBodyTruncated() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateOutboundBodyTruncated()
	})
}

// SetResponseBody sets the "response_body" field.
func (u *TrafficCaptureUpsertBulk) SetResponseBody(v string) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetResponseBody(v)
	})
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateResponseBody() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateResponseBody()
	})
}

// ClearResponseBody clears the value of the "response_body" field.
func (u *TrafficCaptureUpsertBulk) ClearResponseBody() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearResponseBody()
	})
}

// SetResponseBodyBytes sets the "response_body_bytes" field.
func (u *TrafficCaptureUpsertBulk) SetResponseBodyBytes(v int) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetResponseBodyBytes(v)
	})
}

// AddResponseBodyBytes adds v to the "response_body_bytes" field.
func (u *TrafficCaptureUpsertBulk) AddResponseBodyBytes(v int) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.AddResponseBodyBytes(v)
	})
}

// UpdateResponseBodyBytes sets the "response_body_bytes" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateResponseBodyBytes() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateResponseBodyBytes()
	})
}

// SetResponseBodyTruncated sets the "response_body_truncated" field.
func (u *TrafficCaptureUpsertBulk) SetResponseBodyTruncated(v bool) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetResponseBodyTruncated(v)
	})
}

// UpdateResponseBodyTruncated sets the "response_body_truncated" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateResponseBodyTruncated() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateResponseBodyTruncated()
	})
}

// SetOutboundHeaders sets the "outbound_headers" field.
func (u *TrafficCaptureUpsertBulk) SetOutboundHeaders(v map[string]string) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetOutboundHeaders(v)
	})
}

// UpdateOutboundHeaders sets the "outbound_headers" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateOutboundHeaders() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateOutboundHeaders()
	})
}

// ClearOutboundHeaders clears the value of the "outbound_headers" field.
func (u *TrafficCaptureUpsertBulk) ClearOutboundHeaders() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearOutboundHeaders()
	})
}

// SetResponseHeaders sets the "response_headers" field.
func (u *TrafficCaptureUpsertBulk) SetResponseHeaders(v map[string]string) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetResponseHeaders(v)
	})
}

// UpdateResponseHeaders sets the "response_headers" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateResponseHeaders() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateResponseHeaders()
	})
}

// ClearResponseHeaders clears the value of the "response_headers" field.
func (u *TrafficCaptureUpsertBulk) ClearResponseHeaders() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearResponseHeaders()
	})
}

// SetErrorKind sets the "error_kind" field.
func (u *TrafficCaptureUpsertBulk) SetErrorKind(v string) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetErrorKind(v)
	})
}

// UpdateErrorKind sets the "error_kind" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateErrorKind() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateErrorKind()
	})
}

// ClearErrorKind clears the value of the "error_kind" field.
func (u *TrafficCaptureUpsertBulk) ClearErrorKind() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearErrorKind()
	})
}

// SetErrorMsg sets the "error_msg" field.
func (u *TrafficCaptureUpsertBulk) SetErrorMsg(v string) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetErrorMsg(v)
	})
}

// UpdateErrorMsg sets the "error_msg" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateErrorMsg() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateErrorMsg()
	})
}

// ClearErrorMsg clears the value of the "error_msg" field.
func (u *TrafficCaptureUpsertBulk) ClearErrorMsg() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearErrorMsg()
	})
}

// SetClientIP sets the "client_ip" field.
func (u *TrafficCaptureUpsertBulk) SetClientIP(v string) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetClientIP(v)
	})
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateClientIP() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateClientIP()
	})
}

// ClearClientIP clears the value of the "client_ip" field.
func (u *TrafficCaptureUpsertBulk) ClearClientIP() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearClientIP()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *TrafficCaptureUpsertBulk) SetUserAgent(v string) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateUserAgent() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *TrafficCaptureUpsertBulk) ClearUserAgent() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearUserAgent()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *TrafficCaptureUpsertBulk) SetExpiresAt(v time.Time) *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *TrafficCaptureUpsertBulk) UpdateExpiresAt() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *TrafficCaptureUpsertBulk) ClearExpiresAt() *TrafficCaptureUpsertBulk {
	return u.Update(func(s *TrafficCaptureUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *TrafficCaptureUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TrafficCaptureCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TrafficCaptureCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TrafficCaptureUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
