// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/trafficcapture"
)

// TrafficCaptureUpdate is the builder for updating TrafficCapture entities.
type TrafficCaptureUpdate struct {
	config
	hooks    []Hook
	mutation *TrafficCaptureMutation
}

// Where appends a list predicates to the TrafficCaptureUpdate builder.
func (_u *TrafficCaptureUpdate) Where(ps ...predicate.TrafficCapture) *TrafficCaptureUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *TrafficCaptureUpdate) SetRequestID(v string) *TrafficCaptureUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableRequestID(v *string) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *TrafficCaptureUpdate) ClearRequestID() *TrafficCaptureUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (_u *TrafficCaptureUpdate) SetUpstreamRequestID(v string) *TrafficCaptureUpdate {
	_u.mutation.SetUpstreamRequestID(v)
	return _u
}

// SetNillableUpstreamRequestID sets the "upstream_request_id" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableUpstreamRequestID(v *string) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetUpstreamRequestID(*v)
	}
	return _u
}

// ClearUpstreamRequestID clears the value of the "upstream_request_id" field.
func (_u *TrafficCaptureUpdate) ClearUpstreamRequestID() *TrafficCaptureUpdate {
	_u.mutation.ClearUpstreamRequestID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *TrafficCaptureUpdate) SetAPIKeyID(v int64) *TrafficCaptureUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableAPIKeyID(v *int64) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *TrafficCaptureUpdate) AddAPIKeyID(v int64) *TrafficCaptureUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *TrafficCaptureUpdate) ClearAPIKeyID() *TrafficCaptureUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *TrafficCaptureUpdate) SetAccountID(v int64) *TrafficCaptureUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableAccountID(v *int64) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *TrafficCaptureUpdate) AddAccountID(v int64) *TrafficCaptureUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *TrafficCaptureUpdate) ClearAccountID() *TrafficCaptureUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *TrafficCaptureUpdate) SetGroupID(v int64) *TrafficCaptureUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableGroupID(v *int64) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *TrafficCaptureUpdate) AddGroupID(v int64) *TrafficCaptureUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *TrafficCaptureUpdate) ClearGroupID() *TrafficCaptureUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *TrafficCaptureUpdate) SetPlatform(v string) *TrafficCaptureUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillablePlatform(v *string) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// ClearPlatform clears the value of the "platform" field.
func (_u *TrafficCaptureUpdate) ClearPlatform() *TrafficCaptureUpdate {
	_u.mutation.ClearPlatform()
	return _u
}

// SetAccountType sets the "account_type" field.
func (_u *TrafficCaptureUpdate) SetAccountType(v string) *TrafficCaptureUpdate {
	_u.mutation.SetAccountType(v)
	return _u
}

// SetNillableAccountType sets the "account_type" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableAccountType(v *string) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetAccountType(*v)
	}
	return _u
}

// ClearAccountType clears the value of the "account_type" field.
func (_u *TrafficCaptureUpdate) ClearAccountType() *TrafficCaptureUpdate {
	_u.mutation.ClearAccountType()
	return _u
}

// SetModel sets the "model" field.
func (_u *TrafficCaptureUpdate) SetModel(v string) *TrafficCaptureUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableModel(v *string) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *TrafficCaptureUpdate) ClearModel() *TrafficCaptureUpdate {
	_u.mutation.ClearModel()
	return _u
}

// SetUpstreamStatus sets the "upstream_status" field.
func (_u *TrafficCaptureUpdate) SetUpstreamStatus(v int) *TrafficCaptureUpdate {
	_u.mutation.ResetUpstreamStatus()
	_u.mutation.SetUpstreamStatus(v)
	return _u
}

// SetNillableUpstreamStatus sets the "upstream_status" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableUpstreamStatus(v *int) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetUpstreamStatus(*v)
	}
	return _u
}

// AddUpstreamStatus adds value to the "upstream_status" field.
func (_u *TrafficCaptureUpdate) AddUpstreamStatus(v int) *TrafficCaptureUpdate {
	_u.mutation.AddUpstreamStatus(v)
	return _u
}

// SetStream sets the "stream" field.
func (_u *TrafficCaptureUpdate) SetStream(v bool) *TrafficCaptureUpdate {
	_u.mutation.SetStream(v)
	return _u
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableStream(v *bool) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetStream(*v)
	}
	return _u
}

// SetUseTimeMs sets the "use_time_ms" field.
func (_u *TrafficCaptureUpdate) SetUseTimeMs(v int64) *TrafficCaptureUpdate {
	_u.mutation.ResetUseTimeMs()
	_u.mutation.SetUseTimeMs(v)
	return _u
}

// SetNillableUseTimeMs sets the "use_time_ms" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableUseTimeMs(v *int64) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetUseTimeMs(*v)
	}
	return _u
}

// AddUseTimeMs adds value to the "use_time_ms" field.
func (_u *TrafficCaptureUpdate) AddUseTimeMs(v int64) *TrafficCaptureUpdate {
	_u.mutation.AddUseTimeMs(v)
	return _u
}

// SetInboundBody sets the "inbound_body" field.
func (_u *TrafficCaptureUpdate) SetInboundBody(v string) *TrafficCaptureUpdate {
	_u.mutation.SetInboundBody(v)
	return _u
}

// SetNillableInboundBody sets the "inbound_body" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableInboundBody(v *string) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetInboundBody(*v)
	}
	return _u
}

// ClearInboundBody clears the value of the "inbound_body" field.
func (_u *TrafficCaptureUpdate) ClearInboundBody() *TrafficCaptureUpdate {
	_u.mutation.ClearInboundBody()
	return _u
}

// SetInboundBodyBytes sets the "inbound_body_bytes" field.
func (_u *TrafficCaptureUpdate) SetInboundBodyBytes(v int) *TrafficCaptureUpdate {
	_u.mutation.ResetInboundBodyBytes()
	_u.mutation.SetInboundBodyBytes(v)
	return _u
}

// SetNillableInboundBodyBytes sets the "inbound_body_bytes" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableInboundBodyBytes(v *int) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetInboundBodyBytes(*v)
	}
	return _u
}

// AddInboundBodyBytes adds value to the "inbound_body_bytes" field.
func (_u *TrafficCaptureUpdate) AddInboundBodyBytes(v int) *TrafficCaptureUpdate {
	_u.mutation.AddInboundBodyBytes(v)
	return _u
}

// SetInboundBodyTruncated sets the "inbound_body_truncated" field.
func (_u *TrafficCaptureUpdate) SetInboundBodyTruncated(v bool) *TrafficCaptureUpdate {
	_u.mutation.SetInboundBodyTruncated(v)
	return _u
}

// SetNillableInboundBodyTruncated sets the "inbound_body_truncated" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableInboundBodyTruncated(v *bool) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetInboundBodyTruncated(*v)
	}
	return _u
}

// SetOutboundBody sets the "outbound_body" field.
func (_u *TrafficCaptureUpdate) SetOutboundBody(v string) *TrafficCaptureUpdate {
	_u.mutation.SetOutboundBody(v)
	return _u
}

// SetNillableOutboundBody sets the "outbound_body" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableOutboundBody(v *string) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetOutboundBody(*v)
	}
	return _u
}

// ClearOutboundBody clears the value of the "outbound_body" field.
func (_u *TrafficCaptureUpdate) ClearOutboundBody() *TrafficCaptureUpdate {
	_u.mutation.ClearOutboundBody()
	return _u
}

// SetOutboundBodyBytes sets the "outbound_body_bytes" field.
func (_u *TrafficCaptureUpdate) SetOutboundBodyBytes(v int) *TrafficCaptureUpdate {
	_u.mutation.ResetOutboundBodyBytes()
	_u.mutation.SetOutboundBodyBytes(v)
	return _u
}

// SetNillableOutboundBodyBytes sets the "outbound_body_bytes" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableOutboundBodyBytes(v *int) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetOutboundBodyBytes(*v)
	}
	return _u
}

// AddOutboundBodyBytes adds value to the "outbound_body_bytes" field.
func (_u *TrafficCaptureUpdate) AddOutboundBodyBytes(v int) *TrafficCaptureUpdate {
	_u.mutation.AddOutboundBodyBytes(v)
	return _u
}

// SetOutboundBodyTruncated sets the "outbound_body_truncated" field.
func (_u *TrafficCaptureUpdate) SetOutboundBodyTruncated(v bool) *TrafficCaptureUpdate {
	_u.mutation.SetOutboundBodyTruncated(v)
	return _u
}

// SetNillableOutboundBodyTruncated sets the "outbound_body_truncated" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableOutboundBodyTruncated(v *bool) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetOutboundBodyTruncated(*v)
	}
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *TrafficCaptureUpdate) SetResponseBody(v string) *TrafficCaptureUpdate {
	_u.mutation.SetResponseBody(v)
	return _u
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableResponseBody(v *string) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetResponseBody(*v)
	}
	return _u
}

// ClearResponseBody clears the value of the "response_body" field.
func (_u *TrafficCaptureUpdate) ClearResponseBody() *TrafficCaptureUpdate {
	_u.mutation.ClearResponseBody()
	return _u
}

// SetResponseBodyBytes sets the "response_body_bytes" field.
func (_u *TrafficCaptureUpdate) SetResponseBodyBytes(v int) *TrafficCaptureUpdate {
	_u.mutation.ResetResponseBodyBytes()
	_u.mutation.SetResponseBodyBytes(v)
	return _u
}

// SetNillableResponseBodyBytes sets the "response_body_bytes" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableResponseBodyBytes(v *int) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetResponseBodyBytes(*v)
	}
	return _u
}

// AddResponseBodyBytes adds value to the "response_body_bytes" field.
func (_u *TrafficCaptureUpdate) AddResponseBodyBytes(v int) *TrafficCaptureUpdate {
	_u.mutation.AddResponseBodyBytes(v)
	return _u
}

// SetResponseBodyTruncated sets the "response_body_truncated" field.
func (_u *TrafficCaptureUpdate) SetResponseBodyTruncated(v bool) *TrafficCaptureUpdate {
	_u.mutation.SetResponseBodyTruncated(v)
	return _u
}

// SetNillableResponseBodyTruncated sets the "response_body_truncated" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableResponseBodyTruncated(v *bool) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetResponseBodyTruncated(*v)
	}
	return _u
}

// SetOutboundHeaders sets the "outbound_headers" field.
func (_u *TrafficCaptureUpdate) SetOutboundHeaders(v map[string]string) *TrafficCaptureUpdate {
	_u.mutation.SetOutboundHeaders(v)
	return _u
}

// ClearOutboundHeaders clears the value of the "outbound_headers" field.
func (_u *TrafficCaptureUpdate) ClearOutboundHeaders() *TrafficCaptureUpdate {
	_u.mutation.ClearOutboundHeaders()
	return _u
}

// SetResponseHeaders sets the "response_headers" field.
func (_u *TrafficCaptureUpdate) SetResponseHeaders(v map[string]string) *TrafficCaptureUpdate {
	_u.mutation.SetResponseHeaders(v)
	return _u
}

// ClearResponseHeaders clears the value of the "response_headers" field.
func (_u *TrafficCaptureUpdate) ClearResponseHeaders() *TrafficCaptureUpdate {
	_u.mutation.ClearResponseHeaders()
	return _u
}

// SetErrorKind sets the "error_kind" field.
func (_u *TrafficCaptureUpdate) SetErrorKind(v string) *TrafficCaptureUpdate {
	_u.mutation.SetErrorKind(v)
	return _u
}

// SetNillableErrorKind sets the "error_kind" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableErrorKind(v *string) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetErrorKind(*v)
	}
	return _u
}

// ClearErrorKind clears the value of the "error_kind" field.
func (_u *TrafficCaptureUpdate) ClearErrorKind() *TrafficCaptureUpdate {
	_u.mutation.ClearErrorKind()
	return _u
}

// SetErrorMsg sets the "error_msg" field.
func (_u *TrafficCaptureUpdate) SetErrorMsg(v string) *TrafficCaptureUpdate {
	_u.mutation.SetErrorMsg(v)
	return _u
}

// SetNillableErrorMsg sets the "error_msg" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableErrorMsg(v *string) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetErrorMsg(*v)
	}
	return _u
}

// ClearErrorMsg clears the value of the "error_msg" field.
func (_u *TrafficCaptureUpdate) ClearErrorMsg() *TrafficCaptureUpdate {
	_u.mutation.ClearErrorMsg()
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *TrafficCaptureUpdate) SetClientIP(v string) *TrafficCaptureUpdate {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableClientIP(v *string) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// ClearClientIP clears the value of the "client_ip" field.
func (_u *TrafficCaptureUpdate) ClearClientIP() *TrafficCaptureUpdate {
	_u.mutation.ClearClientIP()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *TrafficCaptureUpdate) SetUserAgent(v string) *TrafficCaptureUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableUserAgent(v *string) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *TrafficCaptureUpdate) ClearUserAgent() *TrafficCaptureUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *TrafficCaptureUpdate) SetExpiresAt(v time.Time) *TrafficCaptureUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *TrafficCaptureUpdate) SetNillableExpiresAt(v *time.Time) *TrafficCaptureUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *TrafficCaptureUpdate) ClearExpiresAt() *TrafficCaptureUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the TrafficCaptureMutation object of the builder.
func (_u *TrafficCaptureUpdate) Mutation() *TrafficCaptureMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TrafficCaptureUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TrafficCaptureUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TrafficCaptureUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TrafficCaptureUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TrafficCaptureUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := trafficcapture.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamRequestID(); ok {
		if err := trafficcapture.UpstreamRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_request_id", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.upstream_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := trafficcapture.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountType(); ok {
		if err := trafficcapture.AccountTypeValidator(v); err != nil {
			return &ValidationError{Name: "account_type", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.account_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := trafficcapture.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorKind(); ok {
		if err := trafficcapture.ErrorKindValidator(v); err != nil {
			return &ValidationError{Name: "error_kind", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.error_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMsg(); ok {
		if err := trafficcapture.ErrorMsgValidator(v); err != nil {
			return &ValidationError{Name: "error_msg", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.error_msg": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientIP(); ok {
		if err := trafficcapture.ClientIPValidator(v); err != nil {
			return &ValidationError{Name: "client_ip", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.client_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := trafficcapture.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.user_agent": %w`, err)}
		}
	}
	return nil
}

func (_u *TrafficCaptureUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(trafficcapture.Table, trafficcapture.Columns, sqlgraph.NewFieldSpec(trafficcapture.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(trafficcapture.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(trafficcapture.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamRequestID(); ok {
		_spec.SetField(trafficcapture.FieldUpstreamRequestID, field.TypeString, value)
	}
	if _u.mutation.UpstreamRequestIDCleared() {
		_spec.ClearField(trafficcapture.FieldUpstreamRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(trafficcapture.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(trafficcapture.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(trafficcapture.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(trafficcapture.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(trafficcapture.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(trafficcapture.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(trafficcapture.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(trafficcapture.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(trafficcapture.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(trafficcapture.FieldPlatform, field.TypeString, value)
	}
	if _u.mutation.PlatformCleared() {
		_spec.ClearField(trafficcapture.FieldPlatform, field.TypeString)
	}
	if value, ok := _u.mutation.AccountType(); ok {
		_spec.SetField(trafficcapture.FieldAccountType, field.TypeString, value)
	}
	if _u.mutation.AccountTypeCleared() {
		_spec.ClearField(trafficcapture.FieldAccountType, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(trafficcapture.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(trafficcapture.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamStatus(); ok {
		_spec.SetField(trafficcapture.FieldUpstreamStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpstreamStatus(); ok {
		_spec.AddField(trafficcapture.FieldUpstreamStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Stream(); ok {
		_spec.SetField(trafficcapture.FieldStream, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UseTimeMs(); ok {
		_spec.SetField(trafficcapture.FieldUseTimeMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUseTimeMs(); ok {
		_spec.AddField(trafficcapture.FieldUseTimeMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InboundBody(); ok {
		_spec.SetField(trafficcapture.FieldInboundBody, field.TypeString, value)
	}
	if _u.mutation.InboundBodyCleared() {
		_spec.ClearField(trafficcapture.FieldInboundBody, field.TypeString)
	}
	if value, ok := _u.mutation.InboundBodyBytes(); ok {
		_spec.SetField(trafficcapture.FieldInboundBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInboundBodyBytes(); ok {
		_spec.AddField(trafficcapture.FieldInboundBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InboundBodyTruncated(); ok {
		_spec.SetField(trafficcapture.FieldInboundBodyTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OutboundBody(); ok {
		_spec.SetField(trafficcapture.FieldOutboundBody, field.TypeString, value)
	}
	if _u.mutation.OutboundBodyCleared() {
		_spec.ClearField(trafficcapture.FieldOutboundBody, field.TypeString)
	}
	if value, ok := _u.mutation.OutboundBodyBytes(); ok {
		_spec.SetField(trafficcapture.FieldOutboundBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutboundBodyBytes(); ok {
		_spec.AddField(trafficcapture.FieldOutboundBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OutboundBodyTruncated(); ok {
		_spec.SetField(trafficcapture.FieldOutboundBodyTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(trafficcapture.FieldResponseBody, field.TypeString, value)
	}
	if _u.mutation.ResponseBodyCleared() {
		_spec.ClearField(trafficcapture.FieldResponseBody, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseBodyBytes(); ok {
		_spec.SetField(trafficcapture.FieldResponseBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseBodyBytes(); ok {
		_spec.AddField(trafficcapture.FieldResponseBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResponseBodyTruncated(); ok {
		_spec.SetField(trafficcapture.FieldResponseBodyTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OutboundHeaders(); ok {
		_spec.SetField(trafficcapture.FieldOutboundHeaders, field.TypeJSON, value)
	}
	if _u.mutation.OutboundHeadersCleared() {
		_spec.ClearField(trafficcapture.FieldOutboundHeaders, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResponseHeaders(); ok {
		_spec.SetField(trafficcapture.FieldResponseHeaders, field.TypeJSON, value)
	}
	if _u.mutation.ResponseHeadersCleared() {
		_spec.ClearField(trafficcapture.FieldResponseHeaders, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorKind(); ok {
		_spec.SetField(trafficcapture.FieldErrorKind, field.TypeString, value)
	}
	if _u.mutation.ErrorKindCleared() {
		_spec.ClearField(trafficcapture.FieldErrorKind, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMsg(); ok {
		_spec.SetField(trafficcapture.FieldErrorMsg, field.TypeString, value)
	}
	if _u.mutation.ErrorMsgCleared() {
		_spec.ClearField(trafficcapture.FieldErrorMsg, field.TypeString)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(trafficcapture.FieldClientIP, field.TypeString, value)
	}
	if _u.mutation.ClientIPCleared() {
		_spec.ClearField(trafficcapture.FieldClientIP, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(trafficcapture.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(trafficcapture.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(trafficcapture.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(trafficcapture.FieldExpiresAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{trafficcapture.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TrafficCaptureUpdateOne is the builder for updating a single TrafficCapture entity.
type TrafficCaptureUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TrafficCaptureMutation
}

// SetRequestID sets the "request_id" field.
func (_u *TrafficCaptureUpdateOne) SetRequestID(v string) *TrafficCaptureUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableRequestID(v *string) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *TrafficCaptureUpdateOne) ClearRequestID() *TrafficCaptureUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (_u *TrafficCaptureUpdateOne) SetUpstreamRequestID(v string) *TrafficCaptureUpdateOne {
	_u.mutation.SetUpstreamRequestID(v)
	return _u
}

// SetNillableUpstreamRequestID sets the "upstream_request_id" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableUpstreamRequestID(v *string) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetUpstreamRequestID(*v)
	}
	return _u
}

// ClearUpstreamRequestID clears the value of the "upstream_request_id" field.
func (_u *TrafficCaptureUpdateOne) ClearUpstreamRequestID() *TrafficCaptureUpdateOne {
	_u.mutation.ClearUpstreamRequestID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *TrafficCaptureUpdateOne) SetAPIKeyID(v int64) *TrafficCaptureUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableAPIKeyID(v *int64) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *TrafficCaptureUpdateOne) AddAPIKeyID(v int64) *TrafficCaptureUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *TrafficCaptureUpdateOne) ClearAPIKeyID() *TrafficCaptureUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *TrafficCaptureUpdateOne) SetAccountID(v int64) *TrafficCaptureUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableAccountID(v *int64) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *TrafficCaptureUpdateOne) AddAccountID(v int64) *TrafficCaptureUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *TrafficCaptureUpdateOne) ClearAccountID() *TrafficCaptureUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *TrafficCaptureUpdateOne) SetGroupID(v int64) *TrafficCaptureUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableGroupID(v *int64) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *TrafficCaptureUpdateOne) AddGroupID(v int64) *TrafficCaptureUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *TrafficCaptureUpdateOne) ClearGroupID() *TrafficCaptureUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *TrafficCaptureUpdateOne) SetPlatform(v string) *TrafficCaptureUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillablePlatform(v *string) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// ClearPlatform clears the value of the "platform" field.
func (_u *TrafficCaptureUpdateOne) ClearPlatform() *TrafficCaptureUpdateOne {
	_u.mutation.ClearPlatform()
	return _u
}

// SetAccountType sets the "account_type" field.
func (_u *TrafficCaptureUpdateOne) SetAccountType(v string) *TrafficCaptureUpdateOne {
	_u.mutation.SetAccountType(v)
	return _u
}

// SetNillableAccountType sets the "account_type" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableAccountType(v *string) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetAccountType(*v)
	}
	return _u
}

// ClearAccountType clears the value of the "account_type" field.
func (_u *TrafficCaptureUpdateOne) ClearAccountType() *TrafficCaptureUpdateOne {
	_u.mutation.ClearAccountType()
	return _u
}

// SetModel sets the "model" field.
func (_u *TrafficCaptureUpdateOne) SetModel(v string) *TrafficCaptureUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableModel(v *string) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *TrafficCaptureUpdateOne) ClearModel() *TrafficCaptureUpdateOne {
	_u.mutation.ClearModel()
	return _u
}

// SetUpstreamStatus sets the "upstream_status" field.
func (_u *TrafficCaptureUpdateOne) SetUpstreamStatus(v int) *TrafficCaptureUpdateOne {
	_u.mutation.ResetUpstreamStatus()
	_u.mutation.SetUpstreamStatus(v)
	return _u
}

// SetNillableUpstreamStatus sets the "upstream_status" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableUpstreamStatus(v *int) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetUpstreamStatus(*v)
	}
	return _u
}

// AddUpstreamStatus adds value to the "upstream_status" field.
func (_u *TrafficCaptureUpdateOne) AddUpstreamStatus(v int) *TrafficCaptureUpdateOne {
	_u.mutation.AddUpstreamStatus(v)
	return _u
}

// SetStream sets the "stream" field.
func (_u *TrafficCaptureUpdateOne) SetStream(v bool) *TrafficCaptureUpdateOne {
	_u.mutation.SetStream(v)
	return _u
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableStream(v *bool) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetStream(*v)
	}
	return _u
}

// SetUseTimeMs sets the "use_time_ms" field.
func (_u *TrafficCaptureUpdateOne) SetUseTimeMs(v int64) *TrafficCaptureUpdateOne {
	_u.mutation.ResetUseTimeMs()
	_u.mutation.SetUseTimeMs(v)
	return _u
}

// SetNillableUseTimeMs sets the "use_time_ms" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableUseTimeMs(v *int64) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetUseTimeMs(*v)
	}
	return _u
}

// AddUseTimeMs adds value to the "use_time_ms" field.
func (_u *TrafficCaptureUpdateOne) AddUseTimeMs(v int64) *TrafficCaptureUpdateOne {
	_u.mutation.AddUseTimeMs(v)
	return _u
}

// SetInboundBody sets the "inbound_body" field.
func (_u *TrafficCaptureUpdateOne) SetInboundBody(v string) *TrafficCaptureUpdateOne {
	_u.mutation.SetInboundBody(v)
	return _u
}

// SetNillableInboundBody sets the "inbound_body" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableInboundBody(v *string) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetInboundBody(*v)
	}
	return _u
}

// ClearInboundBody clears the value of the "inbound_body" field.
func (_u *TrafficCaptureUpdateOne) ClearInboundBody() *TrafficCaptureUpdateOne {
	_u.mutation.ClearInboundBody()
	return _u
}

// SetInboundBodyBytes sets the "inbound_body_bytes" field.
func (_u *TrafficCaptureUpdateOne) SetInboundBodyBytes(v int) *TrafficCaptureUpdateOne {
	_u.mutation.ResetInboundBodyBytes()
	_u.mutation.SetInboundBodyBytes(v)
	return _u
}

// SetNillableInboundBodyBytes sets the "inbound_body_bytes" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableInboundBodyBytes(v *int) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetInboundBodyBytes(*v)
	}
	return _u
}

// AddInboundBodyBytes adds value to the "inbound_body_bytes" field.
func (_u *TrafficCaptureUpdateOne) AddInboundBodyBytes(v int) *TrafficCaptureUpdateOne {
	_u.mutation.AddInboundBodyBytes(v)
	return _u
}

// SetInboundBodyTruncated sets the "inbound_body_truncated" field.
func (_u *TrafficCaptureUpdateOne) SetInboundBodyTruncated(v bool) *TrafficCaptureUpdateOne {
	_u.mutation.SetInboundBodyTruncated(v)
	return _u
}

// SetNillableInboundBodyTruncated sets the "inbound_body_truncated" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableInboundBodyTruncated(v *bool) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetInboundBodyTruncated(*v)
	}
	return _u
}

// SetOutboundBody sets the "outbound_body" field.
func (_u *TrafficCaptureUpdateOne) SetOutboundBody(v string) *TrafficCaptureUpdateOne {
	_u.mutation.SetOutboundBody(v)
	return _u
}

// SetNillableOutboundBody sets the "outbound_body" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableOutboundBody(v *string) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetOutboundBody(*v)
	}
	return _u
}

// ClearOutboundBody clears the value of the "outbound_body" field.
func (_u *TrafficCaptureUpdateOne) ClearOutboundBody() *TrafficCaptureUpdateOne {
	_u.mutation.ClearOutboundBody()
	return _u
}

// SetOutboundBodyBytes sets the "outbound_body_bytes" field.
func (_u *TrafficCaptureUpdateOne) SetOutboundBodyBytes(v int) *TrafficCaptureUpdateOne {
	_u.mutation.ResetOutboundBodyBytes()
	_u.mutation.SetOutboundBodyBytes(v)
	return _u
}

// SetNillableOutboundBodyBytes sets the "outbound_body_bytes" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableOutboundBodyBytes(v *int) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetOutboundBodyBytes(*v)
	}
	return _u
}

// AddOutboundBodyBytes adds value to the "outbound_body_bytes" field.
func (_u *TrafficCaptureUpdateOne) AddOutboundBodyBytes(v int) *TrafficCaptureUpdateOne {
	_u.mutation.AddOutboundBodyBytes(v)
	return _u
}

// SetOutboundBodyTruncated sets the "outbound_body_truncated" field.
func (_u *TrafficCaptureUpdateOne) SetOutboundBodyTruncated(v bool) *TrafficCaptureUpdateOne {
	_u.mutation.SetOutboundBodyTruncated(v)
	return _u
}

// SetNillableOutboundBodyTruncated sets the "outbound_body_truncated" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableOutboundBodyTruncated(v *bool) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetOutboundBodyTruncated(*v)
	}
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *TrafficCaptureUpdateOne) SetResponseBody(v string) *TrafficCaptureUpdateOne {
	_u.mutation.SetResponseBody(v)
	return _u
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableResponseBody(v *string) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetResponseBody(*v)
	}
	return _u
}

// ClearResponseBody clears the value of the "response_body" field.
func (_u *TrafficCaptureUpdateOne) ClearResponseBody() *TrafficCaptureUpdateOne {
	_u.mutation.ClearResponseBody()
	return _u
}

// SetResponseBodyBytes sets the "response_body_bytes" field.
func (_u *TrafficCaptureUpdateOne) SetResponseBodyBytes(v int) *TrafficCaptureUpdateOne {
	_u.mutation.ResetResponseBodyBytes()
	_u.mutation.SetResponseBodyBytes(v)
	return _u
}

// SetNillableResponseBodyBytes sets the "response_body_bytes" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableResponseBodyBytes(v *int) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetResponseBodyBytes(*v)
	}
	return _u
}

// AddResponseBodyBytes adds value to the "response_body_bytes" field.
func (_u *TrafficCaptureUpdateOne) AddResponseBodyBytes(v int) *TrafficCaptureUpdateOne {
	_u.mutation.AddResponseBodyBytes(v)
	return _u
}

// SetResponseBodyTruncated sets the "response_body_truncated" field.
func (_u *TrafficCaptureUpdateOne) SetResponseBodyTruncated(v bool) *TrafficCaptureUpdateOne {
	_u.mutation.SetResponseBodyTruncated(v)
	return _u
}

// SetNillableResponseBodyTruncated sets the "response_body_truncated" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableResponseBodyTruncated(v *bool) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetResponseBodyTruncated(*v)
	}
	return _u
}

// SetOutboundHeaders sets the "outbound_headers" field.
func (_u *TrafficCaptureUpdateOne) SetOutboundHeaders(v map[string]string) *TrafficCaptureUpdateOne {
	_u.mutation.SetOutboundHeaders(v)
	return _u
}

// ClearOutboundHeaders clears the value of the "outbound_headers" field.
func (_u *TrafficCaptureUpdateOne) ClearOutboundHeaders() *TrafficCaptureUpdateOne {
	_u.mutation.ClearOutboundHeaders()
	return _u
}

// SetResponseHeaders sets the "response_headers" field.
func (_u *TrafficCaptureUpdateOne) SetResponseHeaders(v map[string]string) *TrafficCaptureUpdateOne {
	_u.mutation.SetResponseHeaders(v)
	return _u
}

// ClearResponseHeaders clears the value of the "response_headers" field.
func (_u *TrafficCaptureUpdateOne) ClearResponseHeaders() *TrafficCaptureUpdateOne {
	_u.mutation.ClearResponseHeaders()
	return _u
}

// SetErrorKind sets the "error_kind" field.
func (_u *TrafficCaptureUpdateOne) SetErrorKind(v string) *TrafficCaptureUpdateOne {
	_u.mutation.SetErrorKind(v)
	return _u
}

// SetNillableErrorKind sets the "error_kind" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableErrorKind(v *string) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetErrorKind(*v)
	}
	return _u
}

// ClearErrorKind clears the value of the "error_kind" field.
func (_u *TrafficCaptureUpdateOne) ClearErrorKind() *TrafficCaptureUpdateOne {
	_u.mutation.ClearErrorKind()
	return _u
}

// SetErrorMsg sets the "error_msg" field.
func (_u *TrafficCaptureUpdateOne) SetErrorMsg(v string) *TrafficCaptureUpdateOne {
	_u.mutation.SetErrorMsg(v)
	return _u
}

// SetNillableErrorMsg sets the "error_msg" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableErrorMsg(v *string) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetErrorMsg(*v)
	}
	return _u
}

// ClearErrorMsg clears the value of the "error_msg" field.
func (_u *TrafficCaptureUpdateOne) ClearErrorMsg() *TrafficCaptureUpdateOne {
	_u.mutation.ClearErrorMsg()
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *TrafficCaptureUpdateOne) SetClientIP(v string) *TrafficCaptureUpdateOne {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableClientIP(v *string) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// ClearClientIP clears the value of the "client_ip" field.
func (_u *TrafficCaptureUpdateOne) ClearClientIP() *TrafficCaptureUpdateOne {
	_u.mutation.ClearClientIP()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *TrafficCaptureUpdateOne) SetUserAgent(v string) *TrafficCaptureUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableUserAgent(v *string) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *TrafficCaptureUpdateOne) ClearUserAgent() *TrafficCaptureUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *TrafficCaptureUpdateOne) SetExpiresAt(v time.Time) *TrafficCaptureUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *TrafficCaptureUpdateOne) SetNillableExpiresAt(v *time.Time) *TrafficCaptureUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *TrafficCaptureUpdateOne) ClearExpiresAt() *TrafficCaptureUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the TrafficCaptureMutation object of the builder.
func (_u *TrafficCaptureUpdateOne) Mutation() *TrafficCaptureMutation {
	return _u.mutation
}

// Where appends a list predicates to the TrafficCaptureUpdate builder.
func (_u *TrafficCaptureUpdateOne) Where(ps ...predicate.TrafficCapture) *TrafficCaptureUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TrafficCaptureUpdateOne) Select(field string, fields ...string) *TrafficCaptureUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TrafficCapture entity.
func (_u *TrafficCaptureUpdateOne) Save(ctx context.Context) (*TrafficCapture, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TrafficCaptureUpdateOne) SaveX(ctx context.Context) *TrafficCapture {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TrafficCaptureUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TrafficCaptureUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TrafficCaptureUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := trafficcapture.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamRequestID(); ok {
		if err := trafficcapture.UpstreamRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_request_id", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.upstream_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := trafficcapture.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountType(); ok {
		if err := trafficcapture.AccountTypeValidator(v); err != nil {
			return &ValidationError{Name: "account_type", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.account_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := trafficcapture.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorKind(); ok {
		if err := trafficcapture.ErrorKindValidator(v); err != nil {
			return &ValidationError{Name: "error_kind", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.error_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMsg(); ok {
		if err := trafficcapture.ErrorMsgValidator(v); err != nil {
			return &ValidationError{Name: "error_msg", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.error_msg": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientIP(); ok {
		if err := trafficcapture.ClientIPValidator(v); err != nil {
			return &ValidationError{Name: "client_ip", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.client_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := trafficcapture.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "TrafficCapture.user_agent": %w`, err)}
		}
	}
	return nil
}

func (_u *TrafficCaptureUpdateOne) sqlSave(ctx context.Context) (_node *TrafficCapture, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(trafficcapture.Table, trafficcapture.Columns, sqlgraph.NewFieldSpec(trafficcapture.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TrafficCapture.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, trafficcapture.FieldID)
		for _, f := range fields {
			if !trafficcapture.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != trafficcapture.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(trafficcapture.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(trafficcapture.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamRequestID(); ok {
		_spec.SetField(trafficcapture.FieldUpstreamRequestID, field.TypeString, value)
	}
	if _u.mutation.UpstreamRequestIDCleared() {
		_spec.ClearField(trafficcapture.FieldUpstreamRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(trafficcapture.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(trafficcapture.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(trafficcapture.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(trafficcapture.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(trafficcapture.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(trafficcapture.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(trafficcapture.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(trafficcapture.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(trafficcapture.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(trafficcapture.FieldPlatform, field.TypeString, value)
	}
	if _u.mutation.PlatformCleared() {
		_spec.ClearField(trafficcapture.FieldPlatform, field.TypeString)
	}
	if value, ok := _u.mutation.AccountType(); ok {
		_spec.SetField(trafficcapture.FieldAccountType, field.TypeString, value)
	}
	if _u.mutation.AccountTypeCleared() {
		_spec.ClearField(trafficcapture.FieldAccountType, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(trafficcapture.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(trafficcapture.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamStatus(); ok {
		_spec.SetField(trafficcapture.FieldUpstreamStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpstreamStatus(); ok {
		_spec.AddField(trafficcapture.FieldUpstreamStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Stream(); ok {
		_spec.SetField(trafficcapture.FieldStream, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UseTimeMs(); ok {
		_spec.SetField(trafficcapture.FieldUseTimeMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUseTimeMs(); ok {
		_spec.AddField(trafficcapture.FieldUseTimeMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InboundBody(); ok {
		_spec.SetField(trafficcapture.FieldInboundBody, field.TypeString, value)
	}
	if _u.mutation.InboundBodyCleared() {
		_spec.ClearField(trafficcapture.FieldInboundBody, field.TypeString)
	}
	if value, ok := _u.mutation.InboundBodyBytes(); ok {
		_spec.SetField(trafficcapture.FieldInboundBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInboundBodyBytes(); ok {
		_spec.AddField(trafficcapture.FieldInboundBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InboundBodyTruncated(); ok {
		_spec.SetField(trafficcapture.FieldInboundBodyTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OutboundBody(); ok {
		_spec.SetField(trafficcapture.FieldOutboundBody, field.TypeString, value)
	}
	if _u.mutation.OutboundBodyCleared() {
		_spec.ClearField(trafficcapture.FieldOutboundBody, field.TypeString)
	}
	if value, ok := _u.mutation.OutboundBodyBytes(); ok {
		_spec.SetField(trafficcapture.FieldOutboundBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutboundBodyBytes(); ok {
		_spec.AddField(trafficcapture.FieldOutboundBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OutboundBodyTruncated(); ok {
		_spec.SetField(trafficcapture.FieldOutboundBodyTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(trafficcapture.FieldResponseBody, field.TypeString, value)
	}
	if _u.mutation.ResponseBodyCleared() {
		_spec.ClearField(trafficcapture.FieldResponseBody, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseBodyBytes(); ok {
		_spec.SetField(trafficcapture.FieldResponseBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseBodyBytes(); ok {
		_spec.AddField(trafficcapture.FieldResponseBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResponseBodyTruncated(); ok {
		_spec.SetField(trafficcapture.FieldResponseBodyTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OutboundHeaders(); ok {
		_spec.SetField(trafficcapture.FieldOutboundHeaders, field.TypeJSON, value)
	}
	if _u.mutation.OutboundHeadersCleared() {
		_spec.ClearField(trafficcapture.FieldOutboundHeaders, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResponseHeaders(); ok {
		_spec.SetField(trafficcapture.FieldResponseHeaders, field.TypeJSON, value)
	}
	if _u.mutation.ResponseHeadersCleared() {
		_spec.ClearField(trafficcapture.FieldResponseHeaders, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorKind(); ok {
		_spec.SetField(trafficcapture.FieldErrorKind, field.TypeString, value)
	}
	if _u.mutation.ErrorKindCleared() {
		_spec.ClearField(trafficcapture.FieldErrorKind, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMsg(); ok {
		_spec.SetField(trafficcapture.FieldErrorMsg, field.TypeString, value)
	}
	if _u.mutation.ErrorMsgCleared() {
		_spec.ClearField(trafficcapture.FieldErrorMsg, field.TypeString)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(trafficcapture.FieldClientIP, field.TypeString, value)
	}
	if _u.mutation.ClientIPCleared() {
		_spec.ClearField(trafficcapture.FieldClientIP, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(trafficcapture.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(trafficcapture.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(trafficcapture.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(trafficcapture.FieldExpiresAt, field.TypeTime)
	}
	_node = &TrafficCapture{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{trafficcapture.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
