// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/trafficcapture"
)

// TrafficCapture is the model entity for the TrafficCapture schema.
type TrafficCapture struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// capture 时间, RFC3339Nano
	Ts time.Time `json:"ts,omitempty"`
	// NewAPI / 客户传的 X-Newapi-Request-Id 或 X-Oneapi-Request-Id
	RequestID string `json:"request_id,omitempty"`
	// 上游 Anthropic/OpenAI 返回的 Request-Id 或 x-request-id
	UpstreamRequestID string `json:"upstream_request_id,omitempty"`
	// sub2api 内部 API key ID, 0 = 未知
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// 绑定的 OAuth/apikey account ID, 0 = 未知
	AccountID int64 `json:"account_id,omitempty"`
	// 绑定的 group ID, 0 = 未知
	GroupID int64 `json:"group_id,omitempty"`
	// anthropic / openai / gemini
	Platform string `json:"platform,omitempty"`
	// oauth / setup-token / apikey
	AccountType string `json:"account_type,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// UpstreamStatus holds the value of the "upstream_status" field.
	UpstreamStatus int `json:"upstream_status,omitempty"`
	// Stream holds the value of the "stream" field.
	Stream bool `json:"stream,omitempty"`
	// 整条链路耗时 (ms)
	UseTimeMs int64 `json:"use_time_ms,omitempty"`
	// 截断到 max_bytes, 见 SUB2API_TRAFFIC_CAPTURE_MAX_BYTES
	InboundBody string `json:"inbound_body,omitempty"`
	// 原始 inbound body 字节数 (截断前)
	InboundBodyBytes int `json:"inbound_body_bytes,omitempty"`
	// InboundBodyTruncated holds the value of the "inbound_body_truncated" field.
	InboundBodyTruncated bool `json:"inbound_body_truncated,omitempty"`
	// sub2api buildUpstreamRequest 之后, 含改写后 OAuth path/metadata/signature
	OutboundBody string `json:"outbound_body,omitempty"`
	// OutboundBodyBytes holds the value of the "outbound_body_bytes" field.
	OutboundBodyBytes int `json:"outbound_body_bytes,omitempty"`
	// OutboundBodyTruncated holds the value of the "outbound_body_truncated" field.
	OutboundBodyTruncated bool `json:"outbound_body_truncated,omitempty"`
	// ResponseBody holds the value of the "response_body" field.
	ResponseBody string `json:"response_body,omitempty"`
	// ResponseBodyBytes holds the value of the "response_body_bytes" field.
	ResponseBodyBytes int `json:"response_body_bytes,omitempty"`
	// ResponseBodyTruncated holds the value of the "response_body_truncated" field.
	ResponseBodyTruncated bool `json:"response_body_truncated,omitempty"`
	// 发给上游的 request header (Authorization / x-api-key 脱敏)
	OutboundHeaders map[string]string `json:"outbound_headers,omitempty"`
	// 上游响应 header snapshot
	ResponseHeaders map[string]string `json:"response_headers,omitempty"`
	// upstream_5xx / upstream_4xx / network / timeout / stream_eof / ''
	ErrorKind string `json:"error_kind,omitempty"`
	// ErrorMsg holds the value of the "error_msg" field.
	ErrorMsg string `json:"error_msg,omitempty"`
	// ClientIP holds the value of the "client_ip" field.
	ClientIP string `json:"client_ip,omitempty"`
	// UserAgent holds the value of the "user_agent" field.
	UserAgent string `json:"user_agent,omitempty"`
	// TTL 到期时间, janitor 清理
	ExpiresAt    time.Time `json:"expires_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TrafficCapture) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case trafficcapture.FieldOutboundHeaders, trafficcapture.FieldResponseHeaders:
			values[i] = new([]byte)
		case trafficcapture.FieldStream, trafficcapture.FieldInboundBodyTruncated, trafficcapture.FieldOutboundBodyTruncated, trafficcapture.FieldResponseBodyTruncated:
			values[i] = new(sql.NullBool)
		case trafficcapture.FieldID, trafficcapture.FieldAPIKeyID, trafficcapture.FieldAccountID, trafficcapture.FieldGroupID, trafficcapture.FieldUpstreamStatus, trafficcapture.FieldUseTimeMs, trafficcapture.FieldInboundBodyBytes, trafficcapture.FieldOutboundBodyBytes, trafficcapture.FieldResponseBodyBytes:
			values[i] = new(sql.NullInt64)
		case trafficcapture.FieldRequestID, trafficcapture.FieldUpstreamRequestID, trafficcapture.FieldPlatform, trafficcapture.FieldAccountType, trafficcapture.FieldModel, trafficcapture.FieldInboundBody, trafficcapture.FieldOutboundBody, trafficcapture.FieldResponseBody, trafficcapture.FieldErrorKind, trafficcapture.FieldErrorMsg, trafficcapture.FieldClientIP, trafficcapture.FieldUserAgent:
			values[i] = new(sql.NullString)
		case trafficcapture.FieldTs, trafficcapture.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TrafficCapture fields.
func (_m *TrafficCapture) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case trafficcapture.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case trafficcapture.FieldTs:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ts", values[i])
			} else if value.Valid {
				_m.Ts = value.Time
			}
		case trafficcapture.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case trafficcapture.FieldUpstreamRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_request_id", values[i])
			} else if value.Valid {
				_m.UpstreamRequestID = value.String
			}
		case trafficcapture.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case trafficcapture.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case trafficcapture.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case trafficcapture.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case trafficcapture.FieldAccountType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_type", values[i])
			} else if value.Valid {
				_m.AccountType = value.String
			}
		case trafficcapture.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case trafficcapture.FieldUpstreamStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_status", values[i])
			} else if value.Valid {
				_m.UpstreamStatus = int(value.Int64)
			}
		case trafficcapture.FieldStream:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field stream", values[i])
			} else if value.Valid {
				_m.Stream = value.Bool
			}
		case trafficcapture.FieldUseTimeMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field use_time_ms", values[i])
			} else if value.Valid {
				_m.UseTimeMs = value.Int64
			}
		case trafficcapture.FieldInboundBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field inbound_body", values[i])
			} else if value.Valid {
				_m.InboundBody = value.String
			}
		case trafficcapture.FieldInboundBodyBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field inbound_body_bytes", values[i])
			} else if value.Valid {
				_m.InboundBodyBytes = int(value.Int64)
			}
		case trafficcapture.FieldInboundBodyTruncated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field inbound_body_truncated", values[i])
			} else if value.Valid {
				_m.InboundBodyTruncated = value.Bool
			}
		case trafficcapture.FieldOutboundBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field outbound_body", values[i])
			} else if value.Valid {
				_m.OutboundBody = value.String
			}
		case trafficcapture.FieldOutboundBodyBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field outbound_body_bytes", values[i])
			} else if value.Valid {
				_m.OutboundBodyBytes = int(value.Int64)
			}
		case trafficcapture.FieldOutboundBodyTruncated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field outbound_body_truncated", values[i])
			} else if value.Valid {
				_m.OutboundBodyTruncated = value.Bool
			}
		case trafficcapture.FieldResponseBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response_body", values[i])
			} else if value.Valid {
				_m.ResponseBody = value.String
			}
		case trafficcapture.FieldResponseBodyBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field response_body_bytes", values[i])
			} else if value.Valid {
				_m.ResponseBodyBytes = int(value.Int64)
			}
		case trafficcapture.FieldResponseBodyTruncated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field response_body_truncated", values[i])
			} else if value.Valid {
				_m.ResponseBodyTruncated = value.Bool
			}
		case trafficcapture.FieldOutboundHeaders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field outbound_headers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.OutboundHeaders); err != nil {
					return fmt.Errorf("unmarshal field outbound_headers: %w", err)
				}
			}
		case trafficcapture.FieldResponseHeaders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field response_headers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResponseHeaders); err != nil {
					return fmt.Errorf("unmarshal field response_headers: %w", err)
				}
			}
		case trafficcapture.FieldErrorKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_kind", values[i])
			} else if value.Valid {
				_m.ErrorKind = value.String
			}
		case trafficcapture.FieldErrorMsg:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_msg", values[i])
			} else if value.Valid {
				_m.ErrorMsg = value.String
			}
		case trafficcapture.FieldClientIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_ip", values[i])
			} else if value.Valid {
				_m.ClientIP = value.String
			}
		case trafficcapture.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = value.String
			}
		case trafficcapture.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TrafficCapture.
// This includes values selected through modifiers, order, etc.
func (_m *TrafficCapture) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TrafficCapture.
// Note that you need to call TrafficCapture.Unwrap() before calling this method if this TrafficCapture
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TrafficCapture) Update() *TrafficCaptureUpdateOne {
	return NewTrafficCaptureClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TrafficCapture entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TrafficCapture) Unwrap() *TrafficCapture {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TrafficCapture is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TrafficCapture) String() string {
	var builder strings.Builder
	builder.WriteString("TrafficCapture(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ts=")
	builder.WriteString(_m.Ts.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("upstream_request_id=")
	builder.WriteString(_m.UpstreamRequestID)
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("account_type=")
	builder.WriteString(_m.AccountType)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("upstream_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpstreamStatus))
	builder.WriteString(", ")
	builder.WriteString("stream=")
	builder.WriteString(fmt.Sprintf("%v", _m.Stream))
	builder.WriteString(", ")
	builder.WriteString("use_time_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.UseTimeMs))
	builder.WriteString(", ")
	builder.WriteString("inbound_body=")
	builder.WriteString(_m.InboundBody)
	builder.WriteString(", ")
	builder.WriteString("inbound_body_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.InboundBodyBytes))
	builder.WriteString(", ")
	builder.WriteString("inbound_body_truncated=")
	builder.WriteString(fmt.Sprintf("%v", _m.InboundBodyTruncated))
	builder.WriteString(", ")
	builder.WriteString("outbound_body=")
	builder.WriteString(_m.OutboundBody)
	builder.WriteString(", ")
	builder.WriteString("outbound_body_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutboundBodyBytes))
	builder.WriteString(", ")
	builder.WriteString("outbound_body_truncated=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutboundBodyTruncated))
	builder.WriteString(", ")
	builder.WriteString("response_body=")
	builder.WriteString(_m.ResponseBody)
	builder.WriteString(", ")
	builder.WriteString("response_body_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseBodyBytes))
	builder.WriteString(", ")
	builder.WriteString("response_body_truncated=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseBodyTruncated))
	builder.WriteString(", ")
	builder.WriteString("outbound_headers=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutboundHeaders))
	builder.WriteString(", ")
	builder.WriteString("response_headers=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseHeaders))
	builder.WriteString(", ")
	builder.WriteString("error_kind=")
	builder.WriteString(_m.ErrorKind)
	builder.WriteString(", ")
	builder.WriteString("error_msg=")
	builder.WriteString(_m.ErrorMsg)
	builder.WriteString(", ")
	builder.WriteString("client_ip=")
	builder.WriteString(_m.ClientIP)
	builder.WriteString(", ")
	builder.WriteString("user_agent=")
	builder.WriteString(_m.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TrafficCaptures is a parsable slice of TrafficCapture.
type TrafficCaptures []*TrafficCapture
