// Code generated by ent, DO NOT EDIT.

package trafficcapture

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the trafficcapture type in the database.
	Label = "traffic_capture"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTs holds the string denoting the ts field in the database.
	FieldTs = "ts"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldUpstreamRequestID holds the string denoting the upstream_request_id field in the database.
	FieldUpstreamRequestID = "upstream_request_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldAccountType holds the string denoting the account_type field in the database.
	FieldAccountType = "account_type"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldUpstreamStatus holds the string denoting the upstream_status field in the database.
	FieldUpstreamStatus = "upstream_status"
	// FieldStream holds the string denoting the stream field in the database.
	FieldStream = "stream"
	// FieldUseTimeMs holds the string denoting the use_time_ms field in the database.
	FieldUseTimeMs = "use_time_ms"
	// FieldInboundBody holds the string denoting the inbound_body field in the database.
	FieldInboundBody = "inbound_body"
	// FieldInboundBodyBytes holds the string denoting the inbound_body_bytes field in the database.
	FieldInboundBodyBytes = "inbound_body_bytes"
	// FieldInboundBodyTruncated holds the string denoting the inbound_body_truncated field in the database.
	FieldInboundBodyTruncated = "inbound_body_truncated"
	// FieldOutboundBody holds the string denoting the outbound_body field in the database.
	FieldOutboundBody = "outbound_body"
	// FieldOutboundBodyBytes holds the string denoting the outbound_body_bytes field in the database.
	FieldOutboundBodyBytes = "outbound_body_bytes"
	// FieldOutboundBodyTruncated holds the string denoting the outbound_body_truncated field in the database.
	FieldOutboundBodyTruncated = "outbound_body_truncated"
	// FieldResponseBody holds the string denoting the response_body field in the database.
	FieldResponseBody = "response_body"
	// FieldResponseBodyBytes holds the string denoting the response_body_bytes field in the database.
	FieldResponseBodyBytes = "response_body_bytes"
	// FieldResponseBodyTruncated holds the string denoting the response_body_truncated field in the database.
	FieldResponseBodyTruncated = "response_body_truncated"
	// FieldOutboundHeaders holds the string denoting the outbound_headers field in the database.
	FieldOutboundHeaders = "outbound_headers"
	// FieldResponseHeaders holds the string denoting the response_headers field in the database.
	FieldResponseHeaders = "response_headers"
	// FieldErrorKind holds the string denoting the error_kind field in the database.
	FieldErrorKind = "error_kind"
	// FieldErrorMsg holds the string denoting the error_msg field in the database.
	FieldErrorMsg = "error_msg"
	// FieldClientIP holds the string denoting the client_ip field in the database.
	FieldClientIP = "client_ip"
	// FieldUserAgent holds the string denoting the user_agent field in the database.
	FieldUserAgent = "user_agent"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// Table holds the table name of the trafficcapture in the database.
	Table = "traffic_captures"
)

// Columns holds all SQL columns for trafficcapture fields.
var Columns = []string{
	FieldID,
	FieldTs,
	FieldRequestID,
	FieldUpstreamRequestID,
	FieldAPIKeyID,
	FieldAccountID,
	FieldGroupID,
	FieldPlatform,
	FieldAccountType,
	FieldModel,
	FieldUpstreamStatus,
	FieldStream,
	FieldUseTimeMs,
	FieldInboundBody,
	FieldInboundBodyBytes,
	FieldInboundBodyTruncated,
	FieldOutboundBody,
	FieldOutboundBodyBytes,
	FieldOutboundBodyTruncated,
	FieldResponseBody,
	FieldResponseBodyBytes,
	FieldResponseBodyTruncated,
	FieldOutboundHeaders,
	FieldResponseHeaders,
	FieldErrorKind,
	FieldErrorMsg,
	FieldClientIP,
	FieldUserAgent,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// UpstreamRequestIDValidator is a validator for the "upstream_request_id" field. It is called by the builders before save.
	UpstreamRequestIDValidator func(string) error
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// AccountTypeValidator is a validator for the "account_type" field. It is called by the builders before save.
	AccountTypeValidator func(string) error
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DefaultUpstreamStatus holds the default value on creation for the "upstream_status" field.
	DefaultUpstreamStatus int
	// DefaultStream holds the default value on creation for the "stream" field.
	DefaultStream bool
	// DefaultUseTimeMs holds the default value on creation for the "use_time_ms" field.
	DefaultUseTimeMs int64
	// DefaultInboundBodyBytes holds the default value on creation for the "inbound_body_bytes" field.
	DefaultInboundBodyBytes int
	// DefaultInboundBodyTruncated holds the default value on creation for the "inbound_body_truncated" field.
	DefaultInboundBodyTruncated bool
	// DefaultOutboundBodyBytes holds the default value on creation for the "outbound_body_bytes" field.
	DefaultOutboundBodyBytes int
	// DefaultOutboundBodyTruncated holds the default value on creation for the "outbound_body_truncated" field.
	DefaultOutboundBodyTruncated bool
	// DefaultResponseBodyBytes holds the default value on creation for the "response_body_bytes" field.
	DefaultResponseBodyBytes int
	// DefaultResponseBodyTruncated holds the default value on creation for the "response_body_truncated" field.
	DefaultResponseBodyTruncated bool
	// ErrorKindValidator is a validator for the "error_kind" field. It is called by the builders before save.
	ErrorKindValidator func(string) error
	// ErrorMsgValidator is a validator for the "error_msg" field. It is called by the builders before save.
	ErrorMsgValidator func(string) error
	// ClientIPValidator is a validator for the "client_ip" field. It is called by the builders before save.
	ClientIPValidator func(string) error
	// UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	UserAgentValidator func(string) error
)

// OrderOption defines the ordering options for the TrafficCapture queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTs orders the results by the ts field.
func ByTs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTs, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByUpstreamRequestID orders the results by the upstream_request_id field.
func ByUpstreamRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamRequestID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByAccountType orders the results by the account_type field.
func ByAccountType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountType, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByUpstreamStatus orders the results by the upstream_status field.
func ByUpstreamStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamStatus, opts...).ToFunc()
}

// ByStream orders the results by the stream field.
func ByStream(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStream, opts...).ToFunc()
}

// ByUseTimeMs orders the results by the use_time_ms field.
func ByUseTimeMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUseTimeMs, opts...).ToFunc()
}

// ByInboundBody orders the results by the inbound_body field.
func ByInboundBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInboundBody, opts...).ToFunc()
}

// ByInboundBodyBytes orders the results by the inbound_body_bytes field.
func ByInboundBodyBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInboundBodyBytes, opts...).ToFunc()
}

// ByInboundBodyTruncated orders the results by the inbound_body_truncated field.
func ByInboundBodyTruncated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInboundBodyTruncated, opts...).ToFunc()
}

// ByOutboundBody orders the results by the outbound_body field.
func ByOutboundBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutboundBody, opts...).ToFunc()
}

// ByOutboundBodyBytes orders the results by the outbound_body_bytes field.
func ByOutboundBodyBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutboundBodyBytes, opts...).ToFunc()
}

// ByOutboundBodyTruncated orders the results by the outbound_body_truncated field.
func ByOutboundBodyTruncated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutboundBodyTruncated, opts...).ToFunc()
}

// ByResponseBody orders the results by the response_body field.
func ByResponseBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseBody, opts...).ToFunc()
}

// ByResponseBodyBytes orders the results by the response_body_bytes field.
func ByResponseBodyBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseBodyBytes, opts...).ToFunc()
}

// ByResponseBodyTruncated orders the results by the response_body_truncated field.
func ByResponseBodyTruncated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseBodyTruncated, opts...).ToFunc()
}

// ByErrorKind orders the results by the error_kind field.
func ByErrorKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorKind, opts...).ToFunc()
}

// ByErrorMsg orders the results by the error_msg field.
func ByErrorMsg(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMsg, opts...).ToFunc()
}

// ByClientIP orders the results by the client_ip field.
func ByClientIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientIP, opts...).ToFunc()
}

// ByUserAgent orders the results by the user_agent field.
func ByUserAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserAgent, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}
