// Code generated by ent, DO NOT EDIT.

package trafficcapture

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldID, id))
}

// Ts applies equality check predicate on the "ts" field. It's identical to TsEQ.
func Ts(v time.Time) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldTs, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldRequestID, v))
}

// UpstreamRequestID applies equality check predicate on the "upstream_request_id" field. It's identical to UpstreamRequestIDEQ.
func UpstreamRequestID(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldUpstreamRequestID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldAPIKeyID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldAccountID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldGroupID, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldPlatform, v))
}

// AccountType applies equality check predicate on the "account_type" field. It's identical to AccountTypeEQ.
func AccountType(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldAccountType, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldModel, v))
}

// UpstreamStatus applies equality check predicate on the "upstream_status" field. It's identical to UpstreamStatusEQ.
func UpstreamStatus(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldUpstreamStatus, v))
}

// Stream applies equality check predicate on the "stream" field. It's identical to StreamEQ.
func Stream(v bool) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldStream, v))
}

// UseTimeMs applies equality check predicate on the "use_time_ms" field. It's identical to UseTimeMsEQ.
func UseTimeMs(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldUseTimeMs, v))
}

// InboundBody applies equality check predicate on the "inbound_body" field. It's identical to InboundBodyEQ.
func InboundBody(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldInboundBody, v))
}

// InboundBodyBytes applies equality check predicate on the "inbound_body_bytes" field. It's identical to InboundBodyBytesEQ.
func InboundBodyBytes(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldInboundBodyBytes, v))
}

// InboundBodyTruncated applies equality check predicate on the "inbound_body_truncated" field. It's identical to InboundBodyTruncatedEQ.
func InboundBodyTruncated(v bool) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldInboundBodyTruncated, v))
}

// OutboundBody applies equality check predicate on the "outbound_body" field. It's identical to OutboundBodyEQ.
func OutboundBody(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldOutboundBody, v))
}

// OutboundBodyBytes applies equality check predicate on the "outbound_body_bytes" field. It's identical to OutboundBodyBytesEQ.
func OutboundBodyBytes(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldOutboundBodyBytes, v))
}

// OutboundBodyTruncated applies equality check predicate on the "outbound_body_truncated" field. It's identical to OutboundBodyTruncatedEQ.
func OutboundBodyTruncated(v bool) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldOutboundBodyTruncated, v))
}

// ResponseBody applies equality check predicate on the "response_body" field. It's identical to ResponseBodyEQ.
func ResponseBody(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldResponseBody, v))
}

// ResponseBodyBytes applies equality check predicate on the "response_body_bytes" field. It's identical to ResponseBodyBytesEQ.
func ResponseBodyBytes(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldResponseBodyBytes, v))
}

// ResponseBodyTruncated applies equality check predicate on the "response_body_truncated" field. It's identical to ResponseBodyTruncatedEQ.
func ResponseBodyTruncated(v bool) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldResponseBodyTruncated, v))
}

// ErrorKind applies equality check predicate on the "error_kind" field. It's identical to ErrorKindEQ.
func ErrorKind(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldErrorKind, v))
}

// ErrorMsg applies equality check predicate on the "error_msg" field. It's identical to ErrorMsgEQ.
func ErrorMsg(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldErrorMsg, v))
}

// ClientIP applies equality check predicate on the "client_ip" field. It's identical to ClientIPEQ.
func ClientIP(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldClientIP, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldUserAgent, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldExpiresAt, v))
}

// TsEQ applies the EQ predicate on the "ts" field.
func TsEQ(v time.Time) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldTs, v))
}

// TsNEQ applies the NEQ predicate on the "ts" field.
func TsNEQ(v time.Time) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldTs, v))
}

// TsIn applies the In predicate on the "ts" field.
func TsIn(vs ...time.Time) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldTs, vs...))
}

// TsNotIn applies the NotIn predicate on the "ts" field.
func TsNotIn(vs ...time.Time) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldTs, vs...))
}

// TsGT applies the GT predicate on the "ts" field.
func TsGT(v time.Time) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldTs, v))
}

// TsGTE applies the GTE predicate on the "ts" field.
func TsGTE(v time.Time) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldTs, v))
}

// TsLT applies the LT predicate on the "ts" field.
func TsLT(v time.Time) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldTs, v))
}

// TsLTE applies the LTE predicate on the "ts" field.
func TsLTE(v time.Time) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldTs, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotNull(FieldRequestID))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContainsFold(FieldRequestID, v))
}

// UpstreamRequestIDEQ applies the EQ predicate on the "upstream_request_id" field.
func UpstreamRequestIDEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDNEQ applies the NEQ predicate on the "upstream_request_id" field.
func UpstreamRequestIDNEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDIn applies the In predicate on the "upstream_request_id" field.
func UpstreamRequestIDIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldUpstreamRequestID, vs...))
}

// UpstreamRequestIDNotIn applies the NotIn predicate on the "upstream_request_id" field.
func UpstreamRequestIDNotIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldUpstreamRequestID, vs...))
}

// UpstreamRequestIDGT applies the GT predicate on the "upstream_request_id" field.
func UpstreamRequestIDGT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDGTE applies the GTE predicate on the "upstream_request_id" field.
func UpstreamRequestIDGTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDLT applies the LT predicate on the "upstream_request_id" field.
func UpstreamRequestIDLT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDLTE applies the LTE predicate on the "upstream_request_id" field.
func UpstreamRequestIDLTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDContains applies the Contains predicate on the "upstream_request_id" field.
func UpstreamRequestIDContains(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContains(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDHasPrefix applies the HasPrefix predicate on the "upstream_request_id" field.
func UpstreamRequestIDHasPrefix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasPrefix(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDHasSuffix applies the HasSuffix predicate on the "upstream_request_id" field.
func UpstreamRequestIDHasSuffix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasSuffix(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDIsNil applies the IsNil predicate on the "upstream_request_id" field.
func UpstreamRequestIDIsNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIsNull(FieldUpstreamRequestID))
}

// UpstreamRequestIDNotNil applies the NotNil predicate on the "upstream_request_id" field.
func UpstreamRequestIDNotNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotNull(FieldUpstreamRequestID))
}

// UpstreamRequestIDEqualFold applies the EqualFold predicate on the "upstream_request_id" field.
func UpstreamRequestIDEqualFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEqualFold(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDContainsFold applies the ContainsFold predicate on the "upstream_request_id" field.
func UpstreamRequestIDContainsFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContainsFold(FieldUpstreamRequestID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldAPIKeyID, v))
}

// APIKeyIDIsNil applies the IsNil predicate on the "api_key_id" field.
func APIKeyIDIsNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIsNull(FieldAPIKeyID))
}

// APIKeyIDNotNil applies the NotNil predicate on the "api_key_id" field.
func APIKeyIDNotNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotNull(FieldAPIKeyID))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotNull(FieldAccountID))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotNull(FieldGroupID))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformIsNil applies the IsNil predicate on the "platform" field.
func PlatformIsNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIsNull(FieldPlatform))
}

// PlatformNotNil applies the NotNil predicate on the "platform" field.
func PlatformNotNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotNull(FieldPlatform))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContainsFold(FieldPlatform, v))
}

// AccountTypeEQ applies the EQ predicate on the "account_type" field.
func AccountTypeEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldAccountType, v))
}

// AccountTypeNEQ applies the NEQ predicate on the "account_type" field.
func AccountTypeNEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldAccountType, v))
}

// AccountTypeIn applies the In predicate on the "account_type" field.
func AccountTypeIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldAccountType, vs...))
}

// AccountTypeNotIn applies the NotIn predicate on the "account_type" field.
func AccountTypeNotIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldAccountType, vs...))
}

// AccountTypeGT applies the GT predicate on the "account_type" field.
func AccountTypeGT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldAccountType, v))
}

// AccountTypeGTE applies the GTE predicate on the "account_type" field.
func AccountTypeGTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldAccountType, v))
}

// AccountTypeLT applies the LT predicate on the "account_type" field.
func AccountTypeLT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldAccountType, v))
}

// AccountTypeLTE applies the LTE predicate on the "account_type" field.
func AccountTypeLTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldAccountType, v))
}

// AccountTypeContains applies the Contains predicate on the "account_type" field.
func AccountTypeContains(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContains(FieldAccountType, v))
}

// AccountTypeHasPrefix applies the HasPrefix predicate on the "account_type" field.
func AccountTypeHasPrefix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasPrefix(FieldAccountType, v))
}

// AccountTypeHasSuffix applies the HasSuffix predicate on the "account_type" field.
func AccountTypeHasSuffix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasSuffix(FieldAccountType, v))
}

// AccountTypeIsNil applies the IsNil predicate on the "account_type" field.
func AccountTypeIsNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIsNull(FieldAccountType))
}

// AccountTypeNotNil applies the NotNil predicate on the "account_type" field.
func AccountTypeNotNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotNull(FieldAccountType))
}

// AccountTypeEqualFold applies the EqualFold predicate on the "account_type" field.
func AccountTypeEqualFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEqualFold(FieldAccountType, v))
}

// AccountTypeContainsFold applies the ContainsFold predicate on the "account_type" field.
func AccountTypeContainsFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContainsFold(FieldAccountType, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasSuffix(FieldModel, v))
}

// ModelIsNil applies the IsNil predicate on the "model" field.
func ModelIsNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIsNull(FieldModel))
}

// ModelNotNil applies the NotNil predicate on the "model" field.
func ModelNotNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotNull(FieldModel))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContainsFold(FieldModel, v))
}

// UpstreamStatusEQ applies the EQ predicate on the "upstream_status" field.
func UpstreamStatusEQ(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldUpstreamStatus, v))
}

// UpstreamStatusNEQ applies the NEQ predicate on the "upstream_status" field.
func UpstreamStatusNEQ(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldUpstreamStatus, v))
}

// UpstreamStatusIn applies the In predicate on the "upstream_status" field.
func UpstreamStatusIn(vs ...int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldUpstreamStatus, vs...))
}

// UpstreamStatusNotIn applies the NotIn predicate on the "upstream_status" field.
func UpstreamStatusNotIn(vs ...int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldUpstreamStatus, vs...))
}

// UpstreamStatusGT applies the GT predicate on the "upstream_status" field.
func UpstreamStatusGT(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldUpstreamStatus, v))
}

// UpstreamStatusGTE applies the GTE predicate on the "upstream_status" field.
func UpstreamStatusGTE(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldUpstreamStatus, v))
}

// UpstreamStatusLT applies the LT predicate on the "upstream_status" field.
func UpstreamStatusLT(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldUpstreamStatus, v))
}

// UpstreamStatusLTE applies the LTE predicate on the "upstream_status" field.
func UpstreamStatusLTE(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldUpstreamStatus, v))
}

// StreamEQ applies the EQ predicate on the "stream" field.
func StreamEQ(v bool) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldStream, v))
}

// StreamNEQ applies the NEQ predicate on the "stream" field.
func StreamNEQ(v bool) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldStream, v))
}

// UseTimeMsEQ applies the EQ predicate on the "use_time_ms" field.
func UseTimeMsEQ(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldUseTimeMs, v))
}

// UseTimeMsNEQ applies the NEQ predicate on the "use_time_ms" field.
func UseTimeMsNEQ(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldUseTimeMs, v))
}

// UseTimeMsIn applies the In predicate on the "use_time_ms" field.
func UseTimeMsIn(vs ...int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldUseTimeMs, vs...))
}

// UseTimeMsNotIn applies the NotIn predicate on the "use_time_ms" field.
func UseTimeMsNotIn(vs ...int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldUseTimeMs, vs...))
}

// UseTimeMsGT applies the GT predicate on the "use_time_ms" field.
func UseTimeMsGT(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldUseTimeMs, v))
}

// UseTimeMsGTE applies the GTE predicate on the "use_time_ms" field.
func UseTimeMsGTE(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldUseTimeMs, v))
}

// UseTimeMsLT applies the LT predicate on the "use_time_ms" field.
func UseTimeMsLT(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldUseTimeMs, v))
}

// UseTimeMsLTE applies the LTE predicate on the "use_time_ms" field.
func UseTimeMsLTE(v int64) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldUseTimeMs, v))
}

// InboundBodyEQ applies the EQ predicate on the "inbound_body" field.
func InboundBodyEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldInboundBody, v))
}

// InboundBodyNEQ applies the NEQ predicate on the "inbound_body" field.
func InboundBodyNEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldInboundBody, v))
}

// InboundBodyIn applies the In predicate on the "inbound_body" field.
func InboundBodyIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldInboundBody, vs...))
}

// InboundBodyNotIn applies the NotIn predicate on the "inbound_body" field.
func InboundBodyNotIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldInboundBody, vs...))
}

// InboundBodyGT applies the GT predicate on the "inbound_body" field.
func InboundBodyGT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldInboundBody, v))
}

// InboundBodyGTE applies the GTE predicate on the "inbound_body" field.
func InboundBodyGTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldInboundBody, v))
}

// InboundBodyLT applies the LT predicate on the "inbound_body" field.
func InboundBodyLT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldInboundBody, v))
}

// InboundBodyLTE applies the LTE predicate on the "inbound_body" field.
func InboundBodyLTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldInboundBody, v))
}

// InboundBodyContains applies the Contains predicate on the "inbound_body" field.
func InboundBodyContains(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContains(FieldInboundBody, v))
}

// InboundBodyHasPrefix applies the HasPrefix predicate on the "inbound_body" field.
func InboundBodyHasPrefix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasPrefix(FieldInboundBody, v))
}

// InboundBodyHasSuffix applies the HasSuffix predicate on the "inbound_body" field.
func InboundBodyHasSuffix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasSuffix(FieldInboundBody, v))
}

// InboundBodyIsNil applies the IsNil predicate on the "inbound_body" field.
func InboundBodyIsNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIsNull(FieldInboundBody))
}

// InboundBodyNotNil applies the NotNil predicate on the "inbound_body" field.
func InboundBodyNotNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotNull(FieldInboundBody))
}

// InboundBodyEqualFold applies the EqualFold predicate on the "inbound_body" field.
func InboundBodyEqualFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEqualFold(FieldInboundBody, v))
}

// InboundBodyContainsFold applies the ContainsFold predicate on the "inbound_body" field.
func InboundBodyContainsFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContainsFold(FieldInboundBody, v))
}

// InboundBodyBytesEQ applies the EQ predicate on the "inbound_body_bytes" field.
func InboundBodyBytesEQ(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldInboundBodyBytes, v))
}

// InboundBodyBytesNEQ applies the NEQ predicate on the "inbound_body_bytes" field.
func InboundBodyBytesNEQ(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldInboundBodyBytes, v))
}

// InboundBodyBytesIn applies the In predicate on the "inbound_body_bytes" field.
func InboundBodyBytesIn(vs ...int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldInboundBodyBytes, vs...))
}

// InboundBodyBytesNotIn applies the NotIn predicate on the "inbound_body_bytes" field.
func InboundBodyBytesNotIn(vs ...int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldInboundBodyBytes, vs...))
}

// InboundBodyBytesGT applies the GT predicate on the "inbound_body_bytes" field.
func InboundBodyBytesGT(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldInboundBodyBytes, v))
}

// InboundBodyBytesGTE applies the GTE predicate on the "inbound_body_bytes" field.
func InboundBodyBytesGTE(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldInboundBodyBytes, v))
}

// InboundBodyBytesLT applies the LT predicate on the "inbound_body_bytes" field.
func InboundBodyBytesLT(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldInboundBodyBytes, v))
}

// InboundBodyBytesLTE applies the LTE predicate on the "inbound_body_bytes" field.
func InboundBodyBytesLTE(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldInboundBodyBytes, v))
}

// InboundBodyTruncatedEQ applies the EQ predicate on the "inbound_body_truncated" field.
func InboundBodyTruncatedEQ(v bool) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldInboundBodyTruncated, v))
}

// InboundBodyTruncatedNEQ applies the NEQ predicate on the "inbound_body_truncated" field.
func InboundBodyTruncatedNEQ(v bool) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldInboundBodyTruncated, v))
}

// OutboundBodyEQ applies the EQ predicate on the "outbound_body" field.
func OutboundBodyEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldOutboundBody, v))
}

// OutboundBodyNEQ applies the NEQ predicate on the "outbound_body" field.
func OutboundBodyNEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldOutboundBody, v))
}

// OutboundBodyIn applies the In predicate on the "outbound_body" field.
func OutboundBodyIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldOutboundBody, vs...))
}

// OutboundBodyNotIn applies the NotIn predicate on the "outbound_body" field.
func OutboundBodyNotIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldOutboundBody, vs...))
}

// OutboundBodyGT applies the GT predicate on the "outbound_body" field.
func OutboundBodyGT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldOutboundBody, v))
}

// OutboundBodyGTE applies the GTE predicate on the "outbound_body" field.
func OutboundBodyGTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldOutboundBody, v))
}

// OutboundBodyLT applies the LT predicate on the "outbound_body" field.
func OutboundBodyLT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldOutboundBody, v))
}

// OutboundBodyLTE applies the LTE predicate on the "outbound_body" field.
func OutboundBodyLTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldOutboundBody, v))
}

// OutboundBodyContains applies the Contains predicate on the "outbound_body" field.
func OutboundBodyContains(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContains(FieldOutboundBody, v))
}

// OutboundBodyHasPrefix applies the HasPrefix predicate on the "outbound_body" field.
func OutboundBodyHasPrefix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasPrefix(FieldOutboundBody, v))
}

// OutboundBodyHasSuffix applies the HasSuffix predicate on the "outbound_body" field.
func OutboundBodyHasSuffix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasSuffix(FieldOutboundBody, v))
}

// OutboundBodyIsNil applies the IsNil predicate on the "outbound_body" field.
func OutboundBodyIsNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIsNull(FieldOutboundBody))
}

// OutboundBodyNotNil applies the NotNil predicate on the "outbound_body" field.
func OutboundBodyNotNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotNull(FieldOutboundBody))
}

// OutboundBodyEqualFold applies the EqualFold predicate on the "outbound_body" field.
func OutboundBodyEqualFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEqualFold(FieldOutboundBody, v))
}

// OutboundBodyContainsFold applies the ContainsFold predicate on the "outbound_body" field.
func OutboundBodyContainsFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContainsFold(FieldOutboundBody, v))
}

// OutboundBodyBytesEQ applies the EQ predicate on the "outbound_body_bytes" field.
func OutboundBodyBytesEQ(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldOutboundBodyBytes, v))
}

// OutboundBodyBytesNEQ applies the NEQ predicate on the "outbound_body_bytes" field.
func OutboundBodyBytesNEQ(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldOutboundBodyBytes, v))
}

// OutboundBodyBytesIn applies the In predicate on the "outbound_body_bytes" field.
func OutboundBodyBytesIn(vs ...int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldOutboundBodyBytes, vs...))
}

// OutboundBodyBytesNotIn applies the NotIn predicate on the "outbound_body_bytes" field.
func OutboundBodyBytesNotIn(vs ...int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldOutboundBodyBytes, vs...))
}

// OutboundBodyBytesGT applies the GT predicate on the "outbound_body_bytes" field.
func OutboundBodyBytesGT(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldOutboundBodyBytes, v))
}

// OutboundBodyBytesGTE applies the GTE predicate on the "outbound_body_bytes" field.
func OutboundBodyBytesGTE(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldOutboundBodyBytes, v))
}

// OutboundBodyBytesLT applies the LT predicate on the "outbound_body_bytes" field.
func OutboundBodyBytesLT(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldOutboundBodyBytes, v))
}

// OutboundBodyBytesLTE applies the LTE predicate on the "outbound_body_bytes" field.
func OutboundBodyBytesLTE(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldOutboundBodyBytes, v))
}

// OutboundBodyTruncatedEQ applies the EQ predicate on the "outbound_body_truncated" field.
func OutboundBodyTruncatedEQ(v bool) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldOutboundBodyTruncated, v))
}

// OutboundBodyTruncatedNEQ applies the NEQ predicate on the "outbound_body_truncated" field.
func OutboundBodyTruncatedNEQ(v bool) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldOutboundBodyTruncated, v))
}

// ResponseBodyEQ applies the EQ predicate on the "response_body" field.
func ResponseBodyEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldResponseBody, v))
}

// ResponseBodyNEQ applies the NEQ predicate on the "response_body" field.
func ResponseBodyNEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldResponseBody, v))
}

// ResponseBodyIn applies the In predicate on the "response_body" field.
func ResponseBodyIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldResponseBody, vs...))
}

// ResponseBodyNotIn applies the NotIn predicate on the "response_body" field.
func ResponseBodyNotIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldResponseBody, vs...))
}

// ResponseBodyGT applies the GT predicate on the "response_body" field.
func ResponseBodyGT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldResponseBody, v))
}

// ResponseBodyGTE applies the GTE predicate on the "response_body" field.
func ResponseBodyGTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldResponseBody, v))
}

// ResponseBodyLT applies the LT predicate on the "response_body" field.
func ResponseBodyLT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldResponseBody, v))
}

// ResponseBodyLTE applies the LTE predicate on the "response_body" field.
func ResponseBodyLTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldResponseBody, v))
}

// ResponseBodyContains applies the Contains predicate on the "response_body" field.
func ResponseBodyContains(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContains(FieldResponseBody, v))
}

// ResponseBodyHasPrefix applies the HasPrefix predicate on the "response_body" field.
func ResponseBodyHasPrefix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasPrefix(FieldResponseBody, v))
}

// ResponseBodyHasSuffix applies the HasSuffix predicate on the "response_body" field.
func ResponseBodyHasSuffix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasSuffix(FieldResponseBody, v))
}

// ResponseBodyIsNil applies the IsNil predicate on the "response_body" field.
func ResponseBodyIsNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIsNull(FieldResponseBody))
}

// ResponseBodyNotNil applies the NotNil predicate on the "response_body" field.
func ResponseBodyNotNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotNull(FieldResponseBody))
}

// ResponseBodyEqualFold applies the EqualFold predicate on the "response_body" field.
func ResponseBodyEqualFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEqualFold(FieldResponseBody, v))
}

// ResponseBodyContainsFold applies the ContainsFold predicate on the "response_body" field.
func ResponseBodyContainsFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContainsFold(FieldResponseBody, v))
}

// ResponseBodyBytesEQ applies the EQ predicate on the "response_body_bytes" field.
func ResponseBodyBytesEQ(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldResponseBodyBytes, v))
}

// ResponseBodyBytesNEQ applies the NEQ predicate on the "response_body_bytes" field.
func ResponseBodyBytesNEQ(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldResponseBodyBytes, v))
}

// ResponseBodyBytesIn applies the In predicate on the "response_body_bytes" field.
func ResponseBodyBytesIn(vs ...int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldResponseBodyBytes, vs...))
}

// ResponseBodyBytesNotIn applies the NotIn predicate on the "response_body_bytes" field.
func ResponseBodyBytesNotIn(vs ...int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldResponseBodyBytes, vs...))
}

// ResponseBodyBytesGT applies the GT predicate on the "response_body_bytes" field.
func ResponseBodyBytesGT(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldResponseBodyBytes, v))
}

// ResponseBodyBytesGTE applies the GTE predicate on the "response_body_bytes" field.
func ResponseBodyBytesGTE(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldResponseBodyBytes, v))
}

// ResponseBodyBytesLT applies the LT predicate on the "response_body_bytes" field.
func ResponseBodyBytesLT(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldResponseBodyBytes, v))
}

// ResponseBodyBytesLTE applies the LTE predicate on the "response_body_bytes" field.
func ResponseBodyBytesLTE(v int) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldResponseBodyBytes, v))
}

// ResponseBodyTruncatedEQ applies the EQ predicate on the "response_body_truncated" field.
func ResponseBodyTruncatedEQ(v bool) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldResponseBodyTruncated, v))
}

// ResponseBodyTruncatedNEQ applies the NEQ predicate on the "response_body_truncated" field.
func ResponseBodyTruncatedNEQ(v bool) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldResponseBodyTruncated, v))
}

// OutboundHeadersIsNil applies the IsNil predicate on the "outbound_headers" field.
func OutboundHeadersIsNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIsNull(FieldOutboundHeaders))
}

// OutboundHeadersNotNil applies the NotNil predicate on the "outbound_headers" field.
func OutboundHeadersNotNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotNull(FieldOutboundHeaders))
}

// ResponseHeadersIsNil applies the IsNil predicate on the "response_headers" field.
func ResponseHeadersIsNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIsNull(FieldResponseHeaders))
}

// ResponseHeadersNotNil applies the NotNil predicate on the "response_headers" field.
func ResponseHeadersNotNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotNull(FieldResponseHeaders))
}

// ErrorKindEQ applies the EQ predicate on the "error_kind" field.
func ErrorKindEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldErrorKind, v))
}

// ErrorKindNEQ applies the NEQ predicate on the "error_kind" field.
func ErrorKindNEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldErrorKind, v))
}

// ErrorKindIn applies the In predicate on the "error_kind" field.
func ErrorKindIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldErrorKind, vs...))
}

// ErrorKindNotIn applies the NotIn predicate on the "error_kind" field.
func ErrorKindNotIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldErrorKind, vs...))
}

// ErrorKindGT applies the GT predicate on the "error_kind" field.
func ErrorKindGT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldErrorKind, v))
}

// ErrorKindGTE applies the GTE predicate on the "error_kind" field.
func ErrorKindGTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldErrorKind, v))
}

// ErrorKindLT applies the LT predicate on the "error_kind" field.
func ErrorKindLT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldErrorKind, v))
}

// ErrorKindLTE applies the LTE predicate on the "error_kind" field.
func ErrorKindLTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldErrorKind, v))
}

// ErrorKindContains applies the Contains predicate on the "error_kind" field.
func ErrorKindContains(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContains(FieldErrorKind, v))
}

// ErrorKindHasPrefix applies the HasPrefix predicate on the "error_kind" field.
func ErrorKindHasPrefix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasPrefix(FieldErrorKind, v))
}

// ErrorKindHasSuffix applies the HasSuffix predicate on the "error_kind" field.
func ErrorKindHasSuffix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasSuffix(FieldErrorKind, v))
}

// ErrorKindIsNil applies the IsNil predicate on the "error_kind" field.
func ErrorKindIsNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIsNull(FieldErrorKind))
}

// ErrorKindNotNil applies the NotNil predicate on the "error_kind" field.
func ErrorKindNotNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotNull(FieldErrorKind))
}

// ErrorKindEqualFold applies the EqualFold predicate on the "error_kind" field.
func ErrorKindEqualFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEqualFold(FieldErrorKind, v))
}

// ErrorKindContainsFold applies the ContainsFold predicate on the "error_kind" field.
func ErrorKindContainsFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContainsFold(FieldErrorKind, v))
}

// ErrorMsgEQ applies the EQ predicate on the "error_msg" field.
func ErrorMsgEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldErrorMsg, v))
}

// ErrorMsgNEQ applies the NEQ predicate on the "error_msg" field.
func ErrorMsgNEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldErrorMsg, v))
}

// ErrorMsgIn applies the In predicate on the "error_msg" field.
func ErrorMsgIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldErrorMsg, vs...))
}

// ErrorMsgNotIn applies the NotIn predicate on the "error_msg" field.
func ErrorMsgNotIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldErrorMsg, vs...))
}

// ErrorMsgGT applies the GT predicate on the "error_msg" field.
func ErrorMsgGT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldErrorMsg, v))
}

// ErrorMsgGTE applies the GTE predicate on the "error_msg" field.
func ErrorMsgGTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldErrorMsg, v))
}

// ErrorMsgLT applies the LT predicate on the "error_msg" field.
func ErrorMsgLT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldErrorMsg, v))
}

// ErrorMsgLTE applies the LTE predicate on the "error_msg" field.
func ErrorMsgLTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldErrorMsg, v))
}

// ErrorMsgContains applies the Contains predicate on the "error_msg" field.
func ErrorMsgContains(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContains(FieldErrorMsg, v))
}

// ErrorMsgHasPrefix applies the HasPrefix predicate on the "error_msg" field.
func ErrorMsgHasPrefix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasPrefix(FieldErrorMsg, v))
}

// ErrorMsgHasSuffix applies the HasSuffix predicate on the "error_msg" field.
func ErrorMsgHasSuffix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasSuffix(FieldErrorMsg, v))
}

// ErrorMsgIsNil applies the IsNil predicate on the "error_msg" field.
func ErrorMsgIsNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIsNull(FieldErrorMsg))
}

// ErrorMsgNotNil applies the NotNil predicate on the "error_msg" field.
func ErrorMsgNotNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotNull(FieldErrorMsg))
}

// ErrorMsgEqualFold applies the EqualFold predicate on the "error_msg" field.
func ErrorMsgEqualFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEqualFold(FieldErrorMsg, v))
}

// ErrorMsgContainsFold applies the ContainsFold predicate on the "error_msg" field.
func ErrorMsgContainsFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContainsFold(FieldErrorMsg, v))
}

// ClientIPEQ applies the EQ predicate on the "client_ip" field.
func ClientIPEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldClientIP, v))
}

// ClientIPNEQ applies the NEQ predicate on the "client_ip" field.
func ClientIPNEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldClientIP, v))
}

// ClientIPIn applies the In predicate on the "client_ip" field.
func ClientIPIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldClientIP, vs...))
}

// ClientIPNotIn applies the NotIn predicate on the "client_ip" field.
func ClientIPNotIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldClientIP, vs...))
}

// ClientIPGT applies the GT predicate on the "client_ip" field.
func ClientIPGT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldClientIP, v))
}

// ClientIPGTE applies the GTE predicate on the "client_ip" field.
func ClientIPGTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldClientIP, v))
}

// ClientIPLT applies the LT predicate on the "client_ip" field.
func ClientIPLT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldClientIP, v))
}

// ClientIPLTE applies the LTE predicate on the "client_ip" field.
func ClientIPLTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldClientIP, v))
}

// ClientIPContains applies the Contains predicate on the "client_ip" field.
func ClientIPContains(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContains(FieldClientIP, v))
}

// ClientIPHasPrefix applies the HasPrefix predicate on the "client_ip" field.
func ClientIPHasPrefix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasPrefix(FieldClientIP, v))
}

// ClientIPHasSuffix applies the HasSuffix predicate on the "client_ip" field.
func ClientIPHasSuffix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasSuffix(FieldClientIP, v))
}

// ClientIPIsNil applies the IsNil predicate on the "client_ip" field.
func ClientIPIsNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIsNull(FieldClientIP))
}

// ClientIPNotNil applies the NotNil predicate on the "client_ip" field.
func ClientIPNotNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotNull(FieldClientIP))
}

// ClientIPEqualFold applies the EqualFold predicate on the "client_ip" field.
func ClientIPEqualFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEqualFold(FieldClientIP, v))
}

// ClientIPContainsFold applies the ContainsFold predicate on the "client_ip" field.
func ClientIPContainsFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContainsFold(FieldClientIP, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentIsNil applies the IsNil predicate on the "user_agent" field.
func UserAgentIsNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIsNull(FieldUserAgent))
}

// UserAgentNotNil applies the NotNil predicate on the "user_agent" field.
func UserAgentNotNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotNull(FieldUserAgent))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldContainsFold(FieldUserAgent, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.FieldNotNull(FieldExpiresAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TrafficCapture) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TrafficCapture) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TrafficCapture) predicate.TrafficCapture {
	return predicate.TrafficCapture(sql.NotPredicates(p))
}
